"""
Auto-generated Pydantic models for Navirec API.

DO NOT EDIT THIS FILE MANUALLY.
Generated from docs/openapi-navirec-1.45.0.json using:
    uv run python scripts/generate_models.py

To regenerate after API spec updates:
    1. Download new OpenAPI spec to docs/
    2. Update OPENAPI_SPEC path in scripts/generate_models.py
    3. Run: uv run python scripts/generate_models.py
"""

# generated by datamodel-codegen:
#   filename:  tmpudlxghr8.json
#   timestamp: 2025-12-31T13:17:47+00:00

from __future__ import annotations

from datetime import date, time
from decimal import Decimal
from enum import Enum, StrEnum
from typing import Annotated, Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, RootModel


class Activity3b5Enum(StrEnum):
    OFFLINE = "offline"
    PARKING = "parking"
    TOWING = "towing"
    IDLING = "idling"
    DRIVING = "driving"


class BlankEnum(Enum):
    FIELD_ = ""


class DefaultLanguageEnum(StrEnum):
    BG = "bg"
    DE = "de"
    EL = "el"
    EN = "en"
    ES = "es"
    ET = "et"
    FI = "fi"
    FR = "fr"
    LT = "lt"
    LV = "lv"
    NL = "nl"
    PL = "pl"
    RU = "ru"


class FuelTypeEnum(StrEnum):
    PETROL = "petrol"
    DIESEL = "diesel"
    HYBRID = "hybrid"
    ELECTRIC = "electric"
    CNG = "cng"
    LPG = "lpg"
    GAS = "gas"
    PETROL_HYBRID = "petrol_hybrid"
    DIESEL_HYBRID = "diesel_hybrid"
    CNG_HYBRID = "cng_hybrid"
    LPG_HYBRID = "lpg_hybrid"


class FuelUsedSourceEnum(StrEnum):
    NOT_SET = "not_set"
    FUEL_LEVEL = "fuel_level"
    TOTAL_FUEL_USED = "total_fuel_used"


class Interpretation676Enum(StrEnum):
    ABSOLUTE_FUEL_RAIL_PRESSURE = "absolute_fuel_rail_pressure"
    ACCELERATOR = "accelerator"
    ACCUMULATED_DISTANCE = "accumulated_distance"
    ACCUMULATED_ENGINE_TIME = "accumulated_engine_time"
    ACCURACY = "accuracy"
    ACTIVITY = "activity"
    ADBLUE_LEVEL_LITRES = "adblue_level_litres"
    ADBLUE_LEVEL_PERCENT = "adblue_level_percent"
    ADDRESS = "address"
    ALARM = "alarm"
    ALTITUDE = "altitude"
    AMBIENT_AIR_TEMPERATURE = "ambient_air_temperature"
    ANALOG_INPUT_1 = "analog_input_1"
    ANALOG_INPUT_2 = "analog_input_2"
    ANALOG_INPUT_3 = "analog_input_3"
    ANALOG_INPUT_4 = "analog_input_4"
    AREA_ID = "area_id"
    AUXILIARY_HEATER = "auxiliary_heater"
    AXLE_LOCATION = "axle_location"
    AXLE_WEIGHT = "axle_weight"
    AXLE_WEIGHT_1 = "axle_weight_1"
    AXLE_WEIGHT_10 = "axle_weight_10"
    AXLE_WEIGHT_11 = "axle_weight_11"
    AXLE_WEIGHT_12 = "axle_weight_12"
    AXLE_WEIGHT_13 = "axle_weight_13"
    AXLE_WEIGHT_14 = "axle_weight_14"
    AXLE_WEIGHT_15 = "axle_weight_15"
    AXLE_WEIGHT_2 = "axle_weight_2"
    AXLE_WEIGHT_3 = "axle_weight_3"
    AXLE_WEIGHT_4 = "axle_weight_4"
    AXLE_WEIGHT_5 = "axle_weight_5"
    AXLE_WEIGHT_6 = "axle_weight_6"
    AXLE_WEIGHT_7 = "axle_weight_7"
    AXLE_WEIGHT_8 = "axle_weight_8"
    AXLE_WEIGHT_9 = "axle_weight_9"
    BAROMETRIC_PRESSURE = "barometric_pressure"
    BATTERY_CURRENT = "battery_current"
    BATTERY_IS_CHARGING = "battery_is_charging"
    BATTERY_LEVEL = "battery_level"
    BATTERY_VOLTAGE = "battery_voltage"
    BLE_BATTERY_1 = "ble_battery_1"
    BLE_BATTERY_2 = "ble_battery_2"
    BLE_BATTERY_3 = "ble_battery_3"
    BLE_BATTERY_4 = "ble_battery_4"
    BLUETOOTH_USER_ID = "bluetooth_user_id"
    BRAKE = "brake"
    CAN_FUEL_LEVEL_LITRES = "can_fuel_level_litres"
    CAN_FUEL_LEVEL_PERCENT = "can_fuel_level_percent"
    CAN_STATE_1 = "can_state_1"
    CAN_STATE_2 = "can_state_2"
    CAN_STATE_3 = "can_state_3"
    CAN_STATE_4 = "can_state_4"
    CAN_SYSTEM_EVENT = "can_system_event"
    CHARGING_CABLE_CONNECTED = "charging_cable_connected"
    CLUTCH = "clutch"
    EGR_COMMANDED = "egr_commanded"
    CONDITION_STARTED_AT = "condition_started_at"
    COUNTRY_ID = "country_id"
    CRASH = "crash"
    CRUISE_CONTROL = "cruise_control"
    DEVICE_ACTIVITY_ID = "device_activity_id"
    DFM_CHEAT = "dfm_cheat"
    DFM_FEED_CHAMBER = "dfm_feed_chamber"
    DFM_INTERFERENCE = "dfm_interference"
    DFM_NEGATIVE = "dfm_negative"
    DFM_REVERSE_CHAMBER = "dfm_reverse_chamber"
    DIGITAL_INPUT_1 = "digital_input_1"
    DIGITAL_INPUT_2 = "digital_input_2"
    DIGITAL_INPUT_3 = "digital_input_3"
    DIGITAL_INPUT_4 = "digital_input_4"
    DIGITAL_INPUT_5 = "digital_input_5"
    DIGITAL_INPUT_6 = "digital_input_6"
    DIGITAL_INPUT_7 = "digital_input_7"
    DIGITAL_INPUT_8 = "digital_input_8"
    DIGITAL_OUTPUT_1 = "digital_output_1"
    DIGITAL_OUTPUT_2 = "digital_output_2"
    DIGITAL_OUTPUT_3 = "digital_output_3"
    DIGITAL_OUTPUT_4 = "digital_output_4"
    DIRECT_FUEL_RAIL_PRESSURE = "direct_fuel_rail_pressure"
    DISTANCE = "distance"
    DTC_CLEARED_DISTANCE = "dtc_cleared_distance"
    MIL_ON_DISTANCE = "mil_on_distance"
    DOOR_STATES = "door_states"
    DRIVER_ID = "driver_id"
    DRIVER_1_ADDITIONAL_INFORMATION = "driver_1_additional_information"
    DRIVER_1_CARD_ID = "driver_1_card_id"
    DRIVER_1_CARD_ID_1 = "driver_1_card_id_1"
    DRIVER_1_CARD_ID_2 = "driver_1_card_id_2"
    DRIVER_1_CARD_ID_3 = "driver_1_card_id_3"
    DRIVER_1_CARD_ID_4 = "driver_1_card_id_4"
    DRIVER_1_CARD_ISSUING_MEMBER_STATE = "driver_1_card_issuing_member_state"
    DRIVER_1_CARD_PRESENCE = "driver_1_card_presence"
    DRIVER_1_CARD_PRESENT = "driver_1_card_present"
    DRIVER_1_CONTINUOUS_DRIVING_TIME = "driver_1_continuous_driving_time"
    DRIVER_1_CUMULATIVE_BREAK_TIME = "driver_1_cumulative_break_time"
    DRIVER_1_CUMULATIVE_DRIVING_TIME = "driver_1_cumulative_driving_time"
    DRIVER_1_DAILY_DRIVING_TIME = "driver_1_daily_driving_time"
    DRIVER_1_NEXT_DRIVING_DURATION = "driver_1_next_driving_duration"
    DRIVER_1_NEXT_REST_DURATION = "driver_1_next_rest_duration"
    DRIVER_1_END_LAST_DAILY_REST_REPORT = "driver_1_end_last_daily_rest_report"
    DRIVER_1_END_LAST_WEEKLY_REST_REPORT = "driver_1_end_last_weekly_rest_report"
    DRIVER_1_END_OF_SECOND_LAST_WEEKLY_REST_REPORT = (
        "driver_1_end_of_second_last_weekly_rest_report"
    )
    DRIVER_1_IBUTTON_ID = "driver_1_ibutton_id"
    DRIVER_1_IBUTTON_ID_1 = "driver_1_ibutton_id_1"
    DRIVER_1_IBUTTON_ID_2 = "driver_1_ibutton_id_2"
    DRIVER_1_LOAD_UNLOAD_TIME = "driver_1_load_unload_time"
    DRIVER_1_MIN_DAILY_REST = "driver_1_min_daily_rest"
    DRIVER_1_MIN_WEEKLY_REST = "driver_1_min_weekly_rest"
    DRIVER_1_NAME = "driver_1_name"
    DRIVER_1_NUMBER_OF_DAILY_DRIVING_TIME_EXCEEDS = (
        "driver_1_number_of_daily_driving_time_exceeds"
    )
    DRIVER_1_OPEN_COMPENSATION_2ND_WEEK_BEFORE_LAST = (
        "driver_1_open_compensation_2nd_week_before_last"
    )
    DRIVER_1_OPEN_COMPENSATION_LAST_WEEK = "driver_1_open_compensation_last_week"
    DRIVER_1_OPEN_COMPENSATION_WEEK_BEFORE_LAST = (
        "driver_1_open_compensation_week_before_last"
    )
    DRIVER_1_REMAINING_CURRENT_DRIVING_TIME = "driver_1_remaining_current_driving_time"
    DRIVER_1_REMAINING_SHIFT_DRIVING_TIME = "driver_1_remaining_shift_driving_time"
    DRIVER_1_REMAINING_WEEKLY_DRIVING_TIME = "driver_1_remaining_weekly_driving_time"
    DRIVER_1_REMAINING_CURRENT_REST_TIME = "driver_1_remaining_current_rest_time"
    DRIVER_1_RFID_ID = "driver_1_rfid_id"
    DRIVER_1_SELECTED_ACTIVITY_DURATION = "driver_1_selected_activity_duration"
    DRIVER_1_SURNAME = "driver_1_surname"
    DRIVER_1_TIME_UNTIL_NEXT_DAILY_REST_PERIOD = (
        "driver_1_time_until_next_daily_rest_period"
    )
    DRIVER_1_TIME_UNTIL_NEXT_WEEKLY_REST_PERIOD = (
        "driver_1_time_until_next_weekly_rest_period"
    )
    DRIVER_1_TIME_UNTIL_NEXT_BREAK = "driver_1_time_until_next_break"
    DRIVER_1_TIME_STATE = "driver_1_time_state"
    DRIVER_1_TIME_UNTIL_NEXT_DRIVING_PERIOD = "driver_1_time_until_next_driving_period"
    DRIVER_1_WEEKLY_DRIVING_TIME = "driver_1_weekly_driving_time"
    DRIVER_1_WORKING_STATE = "driver_1_working_state"
    DRIVER_2_CARD_ID = "driver_2_card_id"
    DRIVER_2_CARD_ID_1 = "driver_2_card_id_1"
    DRIVER_2_CARD_ID_2 = "driver_2_card_id_2"
    DRIVER_2_CARD_ID_3 = "driver_2_card_id_3"
    DRIVER_2_CARD_ID_4 = "driver_2_card_id_4"
    DRIVER_2_CARD_ISSUING_MEMBER_STATE = "driver_2_card_issuing_member_state"
    DRIVER_2_CARD_PRESENCE = "driver_2_card_presence"
    DRIVER_2_CARD_PRESENT = "driver_2_card_present"
    DRIVER_2_CONTINUOUS_DRIVING_TIME = "driver_2_continuous_driving_time"
    DRIVER_2_CUMULATIVE_BREAK_TIME = "driver_2_cumulative_break_time"
    DRIVER_2_CUMULATIVE_DRIVING_TIME = "driver_2_cumulative_driving_time"
    DRIVER_2_DAILY_DRIVING_TIME = "driver_2_daily_driving_time"
    DRIVER_2_NEXT_REST_DURATION = "driver_2_next_rest_duration"
    DRIVER_2_END_LAST_DAILY_REST_REPORT = "driver_2_end_last_daily_rest_report"
    DRIVER_2_END_LAST_WEEKLY_REST_REPORT = "driver_2_end_last_weekly_rest_report"
    DRIVER_2_END_OF_SECOND_LAST_WEEKLY_REST_REPORT = (
        "driver_2_end_of_second_last_weekly_rest_report"
    )
    DRIVER_2_IBUTTON_ID = "driver_2_ibutton_id"
    DRIVER_2_IBUTTON_ID_1 = "driver_2_ibutton_id_1"
    DRIVER_2_IBUTTON_ID_2 = "driver_2_ibutton_id_2"
    DRIVER_2_LOAD_UNLOAD_TIME = "driver_2_load_unload_time"
    DRIVER_2_MIN_DAILY_REST = "driver_2_min_daily_rest"
    DRIVER_2_MIN_WEEKLY_REST = "driver_2_min_weekly_rest"
    DRIVER_2_NAME = "driver_2_name"
    DRIVER_2_NUMBER_OF_DAILY_DRIVING_TIME_EXCEEDS = (
        "driver_2_number_of_daily_driving_time_exceeds"
    )
    DRIVER_2_RFID_ID = "driver_2_rfid_id"
    DRIVER_2_SELECTED_ACTIVITY_DURATION = "driver_2_selected_activity_duration"
    DRIVER_2_SURNAME = "driver_2_surname"
    DRIVER_2_TIME_UNTIL_NEXT_DAILY_REST_PERIOD = (
        "driver_2_time_until_next_daily_rest_period"
    )
    DRIVER_2_TIME_UNTIL_NEXT_WEEKLY_REST_PERIOD = (
        "driver_2_time_until_next_weekly_rest_period"
    )
    DRIVER_2_TIME_UNTIL_NEXT_BREAK = "driver_2_time_until_next_break"
    DRIVER_2_TIME_STATE = "driver_2_time_state"
    DRIVER_2_WEEKLY_DRIVING_TIME = "driver_2_weekly_driving_time"
    DRIVER_2_WORKING_STATE = "driver_2_working_state"
    DRIVER_ADDITIONAL_INFORMATION = "driver_additional_information"
    DRIVER_BREAK_TIME = "driver_break_time"
    DRIVER_CARD_ISSUING_MEMBER_STATE = "driver_card_issuing_member_state"
    DRIVER_CODE = "driver_code"
    DRIVER_CUMULATIVE_BREAK_TIME = "driver_cumulative_break_time"
    DRIVER_CUMULATIVE_DRIVING_TIME = "driver_cumulative_driving_time"
    DRIVER_DAILY_DRIVING_TIME = "driver_daily_driving_time"
    DRIVER_DAILY_DRIVING_TIME_EXCEEDS_COUNT = "driver_daily_driving_time_exceeds_count"
    DRIVER_DAILY_WORK_TIME = "driver_daily_work_time"
    DRIVER_DRIVING_TIME = "driver_driving_time"
    DRIVER_END_LAST_DAILY_REST = "driver_end_last_daily_rest"
    DRIVER_END_LAST_WEEKLY_REST = "driver_end_last_weekly_rest"
    DRIVER_END_SECOND_LAST_WEEKLY_REST = "driver_end_second_last_weekly_rest"
    DRIVER_LOAD_UNLOAD_TIME = "driver_load_unload_time"
    DRIVER_MIN_DAILY_REST = "driver_min_daily_rest"
    DRIVER_MIN_WEEKLY_REST = "driver_min_weekly_rest"
    DRIVER_NAME = "driver_name"
    DRIVER_NEXT_DRIVING_DURATION = "driver_next_driving_duration"
    DRIVER_NEXT_REST_DURATION = "driver_next_rest_duration"
    DRIVER_OPEN_COMPENSATION_2ND_WEEK_BEFORE_LAST = (
        "driver_open_compensation_2nd_week_before_last"
    )
    DRIVER_OPEN_COMPENSATION_LAST_WEEK = "driver_open_compensation_last_week"
    DRIVER_OPEN_COMPENSATION_WEEK_BEFORE_LAST = (
        "driver_open_compensation_week_before_last"
    )
    DRIVER_REMAINING_CURRENT_DRIVING_TIME = "driver_remaining_current_driving_time"
    DRIVER_REMAINING_CURRENT_REST_TIME = "driver_remaining_current_rest_time"
    DRIVER_REMAINING_SHIFT_DRIVING_TIME = "driver_remaining_shift_driving_time"
    DRIVER_REMAINING_WEEKLY_DRIVING_TIME = "driver_remaining_weekly_driving_time"
    DRIVER_SELECTED_ACTIVITY_DURATION = "driver_selected_activity_duration"
    DRIVER_SURNAME = "driver_surname"
    DRIVER_TIME_UNTIL_NEXT_BREAK = "driver_time_until_next_break"
    DRIVER_TIME_UNTIL_NEXT_DAILY_REST = "driver_time_until_next_daily_rest"
    DRIVER_TIME_UNTIL_NEXT_WEEKLY_REST = "driver_time_until_next_weekly_rest"
    DRIVER_TWO_WEEKLY_DRIVING_TIME = "driver_two_weekly_driving_time"
    DRIVER_TWO_WEEKLY_WORK_TIME = "driver_two_weekly_work_time"
    DRIVER_WEEKLY_DRIVING_TIME = "driver_weekly_driving_time"
    DRIVER_WEEKLY_WORK_TIME = "driver_weekly_work_time"
    DRIVER_WORKING_STATE = "driver_working_state"
    DRIVER_WORK_TIME = "driver_work_time"
    DRIVING = "driving"
    ECO_BRAKING_EVENTS = "eco_braking_events"
    ECO_CRUISE_CONTROL_DISTANCE = "eco_cruise_control_distance"
    ECO_CRUISE_CONTROL_TIME = "eco_cruise_control_time"
    ECO_ENGINE_IDLING_TIME = "eco_engine_idling_time"
    ECO_ENGINE_ON_TIME = "eco_engine_on_time"
    ECO_EXTREME_HARSH_BRAKING_EVENTS = "eco_extreme_harsh_braking_events"
    ECO_EXTREME_BRAKING_EVENTS = "eco_extreme_braking_events"
    ECO_HARSH_ACCELERATION_EVENTS = "eco_harsh_acceleration_events"
    ECO_HARSH_BRAKING_EVENTS = "eco_harsh_braking_events"
    ECO_HARSH_CORNERING_EVENTS = "eco_harsh_cornering_events"
    ECO_MAX_RPM = "eco_max_rpm"
    ECO_MAX_SPEED = "eco_max_speed"
    ECO_NORMAL_SPEED_DISTANCE = "eco_normal_speed_distance"
    ECO_OVERSPEED_TIME = "eco_overspeed_time"
    ECO_RPM_GREEN_DISTANCE = "eco_rpm_green_distance"
    ECO_RPM_RED_TIME = "eco_rpm_red_time"
    ECU_VOLTAGE = "ecu_voltage"
    EGR_ERROR = "egr_error"
    ELECT_AC = "elect_ac"
    ELECT_BRAKE_LAMP = "elect_brake_lamp"
    ELECT_ENERGY = "elect_energy"
    ELECT_EV_POWER = "elect_ev_power"
    ELECT_HEADLAMP = "elect_headlamp"
    ELECT_L_TURN_LAMP = "elect_l_turn_lamp"
    ELECT_OCS = "elect_ocs"
    ELECT_OCV = "elect_ocv"
    ELECT_ODOMETER = "elect_odometer"
    ELECT_QCS = "elect_qcs"
    ELECT_RECHARGE_DISTANCE = "elect_recharge_distance"
    ELECT_BATTERY_TEMPERATURE = "elect_battery_temperature"
    ELECT_R_TURN_LAMP = "elect_r_turn_lamp"
    ELECT_SHIFT = "elect_shift"
    ELECT_SOC = "elect_soc"
    ELECT_VELOCITY = "elect_velocity"
    ENGINE_ABSOLUTE_LOAD = "engine_absolute_load"
    ENGINE_COOLANT_TEMPERATURE = "engine_coolant_temperature"
    ENGINE_OIL_TEMPERATURE = "engine_oil_temperature"
    ENGINE_OIL_WARNING = "engine_oil_warning"
    ENGINE_ON_OFF = "engine_on_off"
    ENGINE_PERCENT_LOAD = "engine_percent_load"
    ENGINE_POWER = "engine_power"
    ENGINE_SPEED = "engine_speed"
    ENGINE_TIME = "engine_time"
    ENGINE_TOTAL_FUEL_USED = "engine_total_fuel_used"
    EVENT_COUNT = "event_count"
    FUEL_ECONOMY = "fuel_economy"
    FUEL_INJECTION_TIMING = "fuel_injection_timing"
    FUEL_LEVEL = "fuel_level"
    FUEL_LEVEL_1 = "fuel_level_1"
    FUEL_LEVEL_2 = "fuel_level_2"
    FUEL_LEVEL_3 = "fuel_level_3"
    FUEL_LEVEL_4 = "fuel_level_4"
    FUEL_LEVEL_5 = "fuel_level_5"
    FUEL_LEVEL_6 = "fuel_level_6"
    FUEL_LEVEL_DELTA = "fuel_level_delta"
    FUEL_LEVEL_EWMA = "fuel_level_ewma"
    FUEL_PRESSURE = "fuel_pressure"
    FUEL_RATE = "fuel_rate"
    FUEL_TEMPERATURE = "fuel_temperature"
    FUEL_TEMPERATURE_1 = "fuel_temperature_1"
    FUEL_TEMPERATURE_2 = "fuel_temperature_2"
    FUEL_TEMPERATURE_3 = "fuel_temperature_3"
    FUEL_TEMPERATURE_4 = "fuel_temperature_4"
    FUEL_TEMPERATURE_5 = "fuel_temperature_5"
    FUEL_TEMPERATURE_6 = "fuel_temperature_6"
    GNSS_GDOP = "gnss_gdop"
    GNSS_HDOP = "gnss_hdop"
    GNSS_PDOP = "gnss_pdop"
    GNSS_TDOP = "gnss_tdop"
    GNSS_VDOP = "gnss_vdop"
    GREEN_DRIVING_DURATION = "green_driving_duration"
    GREEN_DRIVING_TYPE = "green_driving_type"
    GREEN_DRIVING_VALUE = "green_driving_value"
    GSM_AREA_CODE = "gsm_area_code"
    GSM_CELL_ID = "gsm_cell_id"
    GSM_OPERATOR_CODE = "gsm_operator_code"
    GSM_SIGNAL = "gsm_signal"
    HEADING = "heading"
    HUMIDITY_1 = "humidity_1"
    HUMIDITY_2 = "humidity_2"
    HUMIDITY_3 = "humidity_3"
    HUMIDITY_4 = "humidity_4"
    HV_BATTERY_CHARGING = "hv_battery_charging"
    HYBRID_BATTERY_LIFE = "hybrid_battery_life"
    IBUTTON_ID = "ibutton_id"
    IDLING = "idling"
    IGNITION = "ignition"
    INTAKE_AIR_TEMPERATURE = "intake_air_temperature"
    INTAKE_MAP = "intake_map"
    JAMMING = "jamming"
    KEYPAD_CODE = "keypad_code"
    LATITUDE = "latitude"
    LOCAL_TIME = "local_time"
    LOCAL_WEEKDAY = "local_weekday"
    LOCATION = "location"
    LONGITUDE = "longitude"
    INTAKE_MAF = "intake_maf"
    ME_BRAKES = "me_brakes"
    ME_DUSK_TIME_INDICATOR = "me_dusk_time_indicator"
    ME_ERROR_CODE = "me_error_code"
    ME_ERROR_VALID = "me_error_valid"
    ME_FAILSAFE_MODE = "me_failsafe_mode"
    ME_FAILSAFE_MODE_TIME = "me_failsafe_mode_time"
    ME_FCW_EVENTS = "me_fcw_events"
    ME_FCW_ON = "me_fcw_on"
    ME_HEADWAY_MEASUREMENT = "me_headway_measurement"
    ME_HEADWAY_VALID = "me_headway_valid"
    ME_HEADWAY_WARNING_EVENTS = "me_headway_warning_events"
    ME_HEADWAY_WARNING_LEVEL = "me_headway_warning_level"
    ME_HW_REPEAT_ENABLED = "me_hw_repeat_enabled"
    ME_HIGH_BEAM = "me_high_beam"
    ME_HIGH_BEAM_AVAILABLE = "me_high_beam_available"
    ME_LDW_EVENTS = "me_ldw_events"
    ME_LDW_OFF = "me_ldw_off"
    ME_LDW_ON = "me_ldw_on"
    ME_LEFT_LDW_EVENTS = "me_left_ldw_events"
    ME_LEFT_LDW_ON = "me_left_ldw_on"
    ME_LEFT_SIGNAL = "me_left_signal"
    ME_LOW_BEAM = "me_low_beam"
    ME_LOW_BEAM_AVAILABLE = "me_low_beam_available"
    ME_MAINTENANCE = "me_maintenance"
    ME_NIGHT_TIME_INDICATOR = "me_night_time_indicator"
    ME_PEDS_FCW = "me_peds_fcw"
    ME_PEDS_FCW_EVENTS = "me_peds_fcw_events"
    ME_PEDS_DZ = "me_peds_dz"
    ME_RIGHT_LDW_EVENTS = "me_right_ldw_events"
    ME_RIGHT_LDW_ON = "me_right_ldw_on"
    ME_RIGHT_SIGNAL = "me_right_signal"
    ME_SIGN_TYPE = "me_sign_type"
    ME_SOUND_TYPE = "me_sound_type"
    ME_SPEED = "me_speed"
    ME_SPEED_AVAILABLE = "me_speed_available"
    ME_TAMPER_ALERT = "me_tamper_alert"
    ME_TAMPER_ALERT_EVENTS = "me_tamper_alert_events"
    ME_TSR_ENABLED = "me_tsr_enabled"
    ME_TSR_MSG = "me_tsr_msg"
    ME_TSR_WARNING_EVENTS = "me_tsr_warning_events"
    ME_TSR_WARNING_LEVEL = "me_tsr_warning_level"
    ME_WIPERS = "me_wipers"
    ME_WIPERS_AVAILABLE = "me_wipers_available"
    ME_ZERO_SPEED = "me_zero_speed"
    MOTION = "motion"
    NAVTELECOM_ACCELERATIONS = "navtelecom_accelerations"
    NAVTELECOM_ACCELEROMETER_STATUS = "navtelecom_accelerometer_status"
    NAVTELECOM_ADBLUE_LEVEL = "navtelecom_adblue_level"
    NAVTELECOM_ADDITIONAL_NAVIGATION_RECEIVER_COORDINA = (
        "navtelecom_additional_navigation_receiver_coordina"
    )
    NAVTELECOM_ADDITIONAL_NAVIGATION_RECIEVER_STATE = (
        "navtelecom_additional_navigation_reciever_state"
    )
    NAVTELECOM_AUTOINFORMER_STATUS = "navtelecom_autoinformer_status"
    NAVTELECOM_CAN_FUEL_LEVEL = "navtelecom_can_fuel_level"
    NAVTELECOM_CAN_SECURITY_FLAGS = "navtelecom_can_security_flags"
    NAVTELECOM_COMMUNICATION_STATUS = "navtelecom_communication_status"
    NAVTELECOM_DEVICE_STATUS = "navtelecom_device_status"
    NAVTELECOM_DIGITAL_INPUTS_3 = "navtelecom_digital_inputs_3"
    NAVTELECOM_DIGITAL_INPUTS_1 = "navtelecom_digital_inputs_1"
    NAVTELECOM_DIGITAL_INPUTS_2 = "navtelecom_digital_inputs_2"
    NAVTELECOM_DIGITAL_OUTPUTS_1 = "navtelecom_digital_outputs_1"
    NAVTELECOM_DIGITAL_OUTPUTS_2 = "navtelecom_digital_outputs_2"
    NAVTELECOM_DILUTION_OF_PRECISION = "navtelecom_dilution_of_precision"
    NAVTELECOM_ECODRIVING_ACCELERATION_THRESHOLD_STATE = (
        "navtelecom_ecodriving_acceleration_threshold_state"
    )
    NAVTELECOM_ECO_PERIOD_MAXIMUM_ACCELERATIONS = (
        "navtelecom_eco_period_maximum_accelerations"
    )
    NAVTELECOM_ECO_DRIVING_SPEED_THRESHOLD_STATES = (
        "navtelecom_eco_driving_speed_threshold_states"
    )
    NAVTELECOM_CAN_EMERGENCY_FLAGS = "navtelecom_can_emergency_flags"
    NAVTELECOM_EXTERNAL_TILT_SENSOR_DEVIATION = (
        "navtelecom_external_tilt_sensor_deviation"
    )
    NAVTELECOM_FAULT_INFORMATION = "navtelecom_fault_information"
    NAVTELECOM_FUEL_FLOW_SENSOR_STATUS = "navtelecom_fuel_flow_sensor_status"
    NAVTELECOM_FUNCTION_MODULES_1 = "navtelecom_function_modules_1"
    NAVTELECOM_FUNCTION_MODULES_2 = "navtelecom_function_modules_2"
    NAVTELECOM_INTERNAL_TILT_SENSOR_ANGLES = "navtelecom_internal_tilt_sensor_angles"
    NAVTELECOM_LBS_INFORMATION = "navtelecom_lbs_information"
    NAVTELECOM_NAVIGATION_INFORMATION = "navtelecom_navigation_information"
    NAVTELECOM_NAVIGATION_STATE = "navtelecom_navigation_state"
    NAVTELECOM_PASSENGER_FLOW_COUNTERS_1 = "navtelecom_passenger_flow_counters_1"
    NAVTELECOM_PASSENGER_FLOW_COUNTERS_2 = "navtelecom_passenger_flow_counters_2"
    NAVTELECOM_REFRIGRERATION_UNIT_STATUS = "navtelecom_refrigreration_unit_status"
    NAVTELECOM_RS485_FUEL_SENSOR_10 = "navtelecom_rs485_fuel_sensor_10"
    NAVTELECOM_RS485_FUEL_SENSOR_11 = "navtelecom_rs485_fuel_sensor_11"
    NAVTELECOM_RS485_FUEL_SENSOR_12 = "navtelecom_rs485_fuel_sensor_12"
    NAVTELECOM_RS485_FUEL_SENSOR_13 = "navtelecom_rs485_fuel_sensor_13"
    NAVTELECOM_RS485_FUEL_SENSOR_14 = "navtelecom_rs485_fuel_sensor_14"
    NAVTELECOM_RS485_FUEL_SENSOR_15 = "navtelecom_rs485_fuel_sensor_15"
    NAVTELECOM_RS485_FUEL_SENSOR_16 = "navtelecom_rs485_fuel_sensor_16"
    NAVTELECOM_RS485_FUEL_SENSOR_7 = "navtelecom_rs485_fuel_sensor_7"
    NAVTELECOM_RS485_FUEL_SENSOR_8 = "navtelecom_rs485_fuel_sensor_8"
    NAVTELECOM_RS485_FUEL_SENSOR_9 = "navtelecom_rs485_fuel_sensor_9"
    NAVTELECOM_TACHO_CARDS = "navtelecom_tacho_cards"
    NAVTELECOM_TACHO_STATUS_FLAGS = "navtelecom_tacho_status_flags"
    NAVTELECOM_TIRE_PRESSURE_SENSORS_4 = "navtelecom_tire_pressure_sensors_4"
    NAVTELECOM_TIRE_PRESSURE_SENSORS_1 = "navtelecom_tire_pressure_sensors_1"
    NAVTELECOM_TIRE_PRESSURE_SENSORS_2 = "navtelecom_tire_pressure_sensors_2"
    NAVTELECOM_TIRE_PRESSURE_SENSORS_3 = "navtelecom_tire_pressure_sensors_3"
    NETWORK_CLIENT_IP = "network_client_ip"
    NETWORK_CLIENT_PORT = "network_client_port"
    NETWORK_HOST_IP = "network_host_ip"
    NETWORK_HOST_PORT = "network_host_port"
    NOTIFICATION = "notification"
    NOTIFICATION_RULE_ID = "notification_rule_id"
    DTC_COUNT = "dtc_count"
    OFFLINE = "offline"
    OUT_OF_ORDER = "out_of_order"
    PANIC = "panic"
    PARKING = "parking"
    PRIORITY = "priority"
    PROTOCOL_DATA = "protocol_data"
    PTO_ENGAGED = "pto_engaged"
    RELATIVE_FUEL_RAIL_PRESSURE = "relative_fuel_rail_pressure"
    RESERVATION_ID = "reservation_id"
    RFID_ID = "rfid_id"
    ROAMING = "roaming"
    SATELLITES = "satellites"
    SCOOTER_ALARM = "scooter_alarm"
    SCOOTER_BUZZER = "scooter_buzzer"
    SCOOTER_CHARGING = "scooter_charging"
    SCOOTER_ERROR = "scooter_error"
    SCOOTER_EXTERNAL_BATTERY = "scooter_external_battery"
    SCOOTER_OPERATION_MODE = "scooter_operation_mode"
    SERVICE_DISTANCE = "service_distance"
    SHORT_TERM_FUEL_TRIM_1 = "short_term_fuel_trim_1"
    SIM_ICCID = "sim_iccid"
    SIM_ICCID_1 = "sim_iccid_1"
    SIM_ICCID_2 = "sim_iccid_2"
    SPEED = "speed"
    SPREADER_BRINE_DOSAGE = "spreader_brine_dosage"
    SPREADER_BRINE_PERCENT = "spreader_brine_percent"
    SPREADER_BRINE_SPREAD = "spreader_brine_spread"
    SPREADER_DRIVEN_DISTANCE = "spreader_driven_distance"
    SPREADER_DRIVEN_TIME = "spreader_driven_time"
    SPREADER_ERROR_CODE = "spreader_error_code"
    SPREADER_LIQUID_MATERIAL = "spreader_liquid_material"
    SPREADER_LIQUID_MATERIAL_1 = "spreader_liquid_material_1"
    SPREADER_LIQUID_MATERIAL_2 = "spreader_liquid_material_2"
    SPREADER_LIQUID_MATERIAL_3 = "spreader_liquid_material_3"
    SPREADER_MAXIMUM = "spreader_maximum"
    SPREADER_MODE = "spreader_mode"
    SPREADER_SOLID_DOSAGE = "spreader_solid_dosage"
    SPREADER_SOLID_MATERIAL = "spreader_solid_material"
    SPREADER_SOLID_MATERIAL_1 = "spreader_solid_material_1"
    SPREADER_SOLID_MATERIAL_2 = "spreader_solid_material_2"
    SPREADER_SOLID_MATERIAL_3 = "spreader_solid_material_3"
    SPREADER_SOLID_SPREAD = "spreader_solid_spread"
    SPREADER_SPEED_ADJUSTMENT = "spreader_speed_adjustment"
    SPREADER_WIDTH = "spreader_width"
    STARTER_BLOCKED = "starter_blocked"
    SUPPLY_VOLTAGE = "supply_voltage"
    TACHO_BORDER_CROSSING_INFO = "tacho_border_crossing_info"
    TACHO_CURRENT_TIME = "tacho_current_time"
    TACHO_DATA_SOURCE = "tacho_data_source"
    TACHO_DIRECTION = "tacho_direction"
    TACHO_DRIVE_RECOGNIZE = "tacho_drive_recognize"
    TACHO_DRIVERS_DATA_CONSENT = "tacho_drivers_data_consent"
    TACHO_DRIVERS_HOURS_RULES_PRE_WARNING_TIME_DELAY = (
        "tacho_drivers_hours_rules_pre_warning_time_delay"
    )
    TACHOGRAPH_CARD_ID = "tachograph_card_id"
    TACHO_HANDLING_INFO = "tacho_handling_info"
    TACHO_K_LINE_PRIVACY_MODE = "tacho_k_line_privacy_mode"
    TACHO_NEXT_CALIBRATION_DATE = "tacho_next_calibration_date"
    TACHO_OUT_OF_SCOPE_CONDITION = "tacho_out_of_scope_condition"
    TACHO_PERFORM = "tacho_perform"
    TACHO_TRIP = "tacho_trip"
    TACHO_VEHICLE_ID = "tacho_vehicle_id"
    TACHO_VEHICLE_ID_1 = "tacho_vehicle_id_1"
    TACHO_VEHICLE_ID_2 = "tacho_vehicle_id_2"
    TACHO_VEHICLE_ID_3 = "tacho_vehicle_id_3"
    TACHO_VEHICLE_LOAD_TYPE_INFO = "tacho_vehicle_load_type_info"
    TACHO_VEHICLE_MOTION = "tacho_vehicle_motion"
    TACHO_VEHICLE_OVERSPEED = "tacho_vehicle_overspeed"
    TACHO_VEHICLE_SPEED = "tacho_vehicle_speed"
    TELTONIKA_AGRICULTURAL_STATE_FLAGS_P4 = "teltonika_agricultural_state_flags_p4"
    TELTONIKA_BLE_CUSTOM_1 = "teltonika_ble_custom_1"
    TELTONIKA_BLE_CUSTOM_2 = "teltonika_ble_custom_2"
    TELTONIKA_BLE_CUSTOM_3 = "teltonika_ble_custom_3"
    TELTONIKA_BLE_CUSTOM_4 = "teltonika_ble_custom_4"
    TELTONIKA_BLUETOOTH_STATUS = "teltonika_bluetooth_status"
    TELTONIKA_CISTERN_STATE_FLAGS_P4 = "teltonika_cistern_state_flags_p4"
    TELTONIKA_CONTROL_STATE_FLAGS_P2 = "teltonika_control_state_flags_p2"
    TELTONIKA_CONTROL_STATE_FLAGS_P4 = "teltonika_control_state_flags_p4"
    TELTONIKA_DATA_MODE = "teltonika_data_mode"
    TELTONIKA_EXTERNAL_DIGITAL_SENSOR_1 = "teltonika_external_digital_sensor_1"
    TELTONIKA_GNSS_STATUS = "teltonika_gnss_status"
    TELTONIKA_INDICATOR_STATE_FLAGS_P4 = "teltonika_indicator_state_flags_p4"
    TELTONIKA_LVCAN_PROGRAM_NUMBER = "teltonika_lvcan_program_number"
    TELTONIKA_SECURITY_STATE_FLAGS_P2 = "teltonika_security_state_flags_p2"
    TELTONIKA_SECURITY_STATE_FLAGS_P4 = "teltonika_security_state_flags_p4"
    TELTONIKA_SLEEP_MODE = "teltonika_sleep_mode"
    TELTONIKA_TEMPERATURE_PROBE_1 = "teltonika_temperature_probe_1"
    TELTONIKA_TEMPERATURE_PROBE_2 = "teltonika_temperature_probe_2"
    TELTONIKA_TEMPERATURE_PROBE_3 = "teltonika_temperature_probe_3"
    TELTONIKA_TEMPERATURE_PROBE_4 = "teltonika_temperature_probe_4"
    TELTONIKA_TEMPERATURE_PROBE_5 = "teltonika_temperature_probe_5"
    TELTONIKA_TEMPERATURE_PROBE_6 = "teltonika_temperature_probe_6"
    TELTONIKA_TRIP = "teltonika_trip"
    TELTONIKA_UTILITY_STATE_FLAGS_P4 = "teltonika_utility_state_flags_p4"
    TELTONIKA_ZONE_1_SET_TEMPERATURE = "teltonika_zone_1_set_temperature"
    TELTONIKA_ZONE_2_SET_TEMPERATURE = "teltonika_zone_2_set_temperature"
    TEMPERATURE_1 = "temperature_1"
    TEMPERATURE_2 = "temperature_2"
    TEMPERATURE_3 = "temperature_3"
    TEMPERATURE_4 = "temperature_4"
    TEMPERATURE_5 = "temperature_5"
    TEMPERATURE_6 = "temperature_6"
    TEMPERATURE_7 = "temperature_7"
    TEMPERATURE_8 = "temperature_8"
    MIL_ON_TIME = "mil_on_time"
    TIME_SINCE_ENGINE_START = "time_since_engine_start"
    DTC_CLEARED_TIME = "dtc_cleared_time"
    TIMEZONE_OFFSET = "timezone_offset"
    TIMING_ADVANCE = "timing_advance"
    TOTAL_DIN1_TIME = "total_din1_time"
    TOTAL_DIN2_TIME = "total_din2_time"
    TOTAL_DIN3_TIME = "total_din3_time"
    TOTAL_DIN4_TIME = "total_din4_time"
    TOTAL_DISTANCE = "total_distance"
    TOTAL_ENGINE_TIME = "total_engine_time"
    TOTAL_FUEL_USED = "total_fuel_used"
    TOTAL_GPS_DISTANCE = "total_gps_distance"
    TOWING = "towing"
    TRAIL = "trail"
    TRIP_TYPE = "trip_type"
    TRIP_TYPE_PRIVATE = "trip_type_private"
    TRIP_TYPE_WORK = "trip_type_work"
    UNPLUG = "unplug"
    VEHICLE_ID = "vehicle_id"
    VEHICLE_LOCKED = "vehicle_locked"
    VEHICLE_WEIGHT = "vehicle_weight"
    VIN = "vin"
    VIN_1 = "vin_1"
    VIN_2 = "vin_2"
    VIN_3 = "vin_3"
    WHEEL_BASED_SPEED = "wheel_based_speed"
    WITHIN_AREA_IDS = "within_area_ids"


class NullEnum(Enum):
    NONE_TYPE_NONE = None


class Interpretation(RootModel[Interpretation676Enum]):
    root: Interpretation676Enum


class Sensor(BaseModel):
    id: UUID | None = None
    url: AnyUrl | None = None
    vehicle: AnyUrl | None = None
    interpretation: Interpretation | None = None
    name: Annotated[str | None, Field(max_length=128)] = None
    name_display: str | None = None
    slug: Annotated[str | None, Field(pattern="^[-a-zA-Z0-9_]+$")] = None
    icon: AnyUrl | None = None
    icon_template_vars: Any | None = None
    color: str | None = None
    min_value: Annotated[int | None, Field(title="Minimum value")] = None
    max_value: Annotated[int | None, Field(title="Maximum value")] = None
    show_in_map: bool
    show_in_list: bool
    show_in_icon: bool
    show_in_chart: bool
    show_in_report: bool
    sort_order: int | None = None
    chart_axis_id: Annotated[str | None, Field(title="Chart exit ID")] = None


class TimezoneEnum(StrEnum):
    AFRICA_ABIDJAN = "Africa/Abidjan"
    AFRICA_ACCRA = "Africa/Accra"
    AFRICA_ADDIS_ABABA = "Africa/Addis_Ababa"
    AFRICA_ALGIERS = "Africa/Algiers"
    AFRICA_ASMARA = "Africa/Asmara"
    AFRICA_ASMERA = "Africa/Asmera"
    AFRICA_BAMAKO = "Africa/Bamako"
    AFRICA_BANGUI = "Africa/Bangui"
    AFRICA_BANJUL = "Africa/Banjul"
    AFRICA_BISSAU = "Africa/Bissau"
    AFRICA_BLANTYRE = "Africa/Blantyre"
    AFRICA_BRAZZAVILLE = "Africa/Brazzaville"
    AFRICA_BUJUMBURA = "Africa/Bujumbura"
    AFRICA_CAIRO = "Africa/Cairo"
    AFRICA_CASABLANCA = "Africa/Casablanca"
    AFRICA_CEUTA = "Africa/Ceuta"
    AFRICA_CONAKRY = "Africa/Conakry"
    AFRICA_DAKAR = "Africa/Dakar"
    AFRICA_DAR_ES_SALAAM = "Africa/Dar_es_Salaam"
    AFRICA_DJIBOUTI = "Africa/Djibouti"
    AFRICA_DOUALA = "Africa/Douala"
    AFRICA_EL_AAIUN = "Africa/El_Aaiun"
    AFRICA_FREETOWN = "Africa/Freetown"
    AFRICA_GABORONE = "Africa/Gaborone"
    AFRICA_HARARE = "Africa/Harare"
    AFRICA_JOHANNESBURG = "Africa/Johannesburg"
    AFRICA_JUBA = "Africa/Juba"
    AFRICA_KAMPALA = "Africa/Kampala"
    AFRICA_KHARTOUM = "Africa/Khartoum"
    AFRICA_KIGALI = "Africa/Kigali"
    AFRICA_KINSHASA = "Africa/Kinshasa"
    AFRICA_LAGOS = "Africa/Lagos"
    AFRICA_LIBREVILLE = "Africa/Libreville"
    AFRICA_LOME = "Africa/Lome"
    AFRICA_LUANDA = "Africa/Luanda"
    AFRICA_LUBUMBASHI = "Africa/Lubumbashi"
    AFRICA_LUSAKA = "Africa/Lusaka"
    AFRICA_MALABO = "Africa/Malabo"
    AFRICA_MAPUTO = "Africa/Maputo"
    AFRICA_MASERU = "Africa/Maseru"
    AFRICA_MBABANE = "Africa/Mbabane"
    AFRICA_MOGADISHU = "Africa/Mogadishu"
    AFRICA_MONROVIA = "Africa/Monrovia"
    AFRICA_NAIROBI = "Africa/Nairobi"
    AFRICA_NDJAMENA = "Africa/Ndjamena"
    AFRICA_NIAMEY = "Africa/Niamey"
    AFRICA_NOUAKCHOTT = "Africa/Nouakchott"
    AFRICA_OUAGADOUGOU = "Africa/Ouagadougou"
    AFRICA_PORTO_NOVO = "Africa/Porto-Novo"
    AFRICA_SAO_TOME = "Africa/Sao_Tome"
    AFRICA_TIMBUKTU = "Africa/Timbuktu"
    AFRICA_TRIPOLI = "Africa/Tripoli"
    AFRICA_TUNIS = "Africa/Tunis"
    AFRICA_WINDHOEK = "Africa/Windhoek"
    AMERICA_ADAK = "America/Adak"
    AMERICA_ANCHORAGE = "America/Anchorage"
    AMERICA_ANGUILLA = "America/Anguilla"
    AMERICA_ANTIGUA = "America/Antigua"
    AMERICA_ARAGUAINA = "America/Araguaina"
    AMERICA_ARGENTINA_BUENOS_AIRES = "America/Argentina/Buenos_Aires"
    AMERICA_ARGENTINA_CATAMARCA = "America/Argentina/Catamarca"
    AMERICA_ARGENTINA_COMOD_RIVADAVIA = "America/Argentina/ComodRivadavia"
    AMERICA_ARGENTINA_CORDOBA = "America/Argentina/Cordoba"
    AMERICA_ARGENTINA_JUJUY = "America/Argentina/Jujuy"
    AMERICA_ARGENTINA_LA_RIOJA = "America/Argentina/La_Rioja"
    AMERICA_ARGENTINA_MENDOZA = "America/Argentina/Mendoza"
    AMERICA_ARGENTINA_RIO_GALLEGOS = "America/Argentina/Rio_Gallegos"
    AMERICA_ARGENTINA_SALTA = "America/Argentina/Salta"
    AMERICA_ARGENTINA_SAN_JUAN = "America/Argentina/San_Juan"
    AMERICA_ARGENTINA_SAN_LUIS = "America/Argentina/San_Luis"
    AMERICA_ARGENTINA_TUCUMAN = "America/Argentina/Tucuman"
    AMERICA_ARGENTINA_USHUAIA = "America/Argentina/Ushuaia"
    AMERICA_ARUBA = "America/Aruba"
    AMERICA_ASUNCION = "America/Asuncion"
    AMERICA_ATIKOKAN = "America/Atikokan"
    AMERICA_ATKA = "America/Atka"
    AMERICA_BAHIA = "America/Bahia"
    AMERICA_BAHIA_BANDERAS = "America/Bahia_Banderas"
    AMERICA_BARBADOS = "America/Barbados"
    AMERICA_BELEM = "America/Belem"
    AMERICA_BELIZE = "America/Belize"
    AMERICA_BLANC_SABLON = "America/Blanc-Sablon"
    AMERICA_BOA_VISTA = "America/Boa_Vista"
    AMERICA_BOGOTA = "America/Bogota"
    AMERICA_BOISE = "America/Boise"
    AMERICA_BUENOS_AIRES = "America/Buenos_Aires"
    AMERICA_CAMBRIDGE_BAY = "America/Cambridge_Bay"
    AMERICA_CAMPO_GRANDE = "America/Campo_Grande"
    AMERICA_CANCUN = "America/Cancun"
    AMERICA_CARACAS = "America/Caracas"
    AMERICA_CATAMARCA = "America/Catamarca"
    AMERICA_CAYENNE = "America/Cayenne"
    AMERICA_CAYMAN = "America/Cayman"
    AMERICA_CHICAGO = "America/Chicago"
    AMERICA_CHIHUAHUA = "America/Chihuahua"
    AMERICA_CIUDAD_JUAREZ = "America/Ciudad_Juarez"
    AMERICA_CORAL_HARBOUR = "America/Coral_Harbour"
    AMERICA_CORDOBA = "America/Cordoba"
    AMERICA_COSTA_RICA = "America/Costa_Rica"
    AMERICA_COYHAIQUE = "America/Coyhaique"
    AMERICA_CRESTON = "America/Creston"
    AMERICA_CUIABA = "America/Cuiaba"
    AMERICA_CURACAO = "America/Curacao"
    AMERICA_DANMARKSHAVN = "America/Danmarkshavn"
    AMERICA_DAWSON = "America/Dawson"
    AMERICA_DAWSON_CREEK = "America/Dawson_Creek"
    AMERICA_DENVER = "America/Denver"
    AMERICA_DETROIT = "America/Detroit"
    AMERICA_DOMINICA = "America/Dominica"
    AMERICA_EDMONTON = "America/Edmonton"
    AMERICA_EIRUNEPE = "America/Eirunepe"
    AMERICA_EL_SALVADOR = "America/El_Salvador"
    AMERICA_ENSENADA = "America/Ensenada"
    AMERICA_FORT_NELSON = "America/Fort_Nelson"
    AMERICA_FORT_WAYNE = "America/Fort_Wayne"
    AMERICA_FORTALEZA = "America/Fortaleza"
    AMERICA_GLACE_BAY = "America/Glace_Bay"
    AMERICA_GODTHAB = "America/Godthab"
    AMERICA_GOOSE_BAY = "America/Goose_Bay"
    AMERICA_GRAND_TURK = "America/Grand_Turk"
    AMERICA_GRENADA = "America/Grenada"
    AMERICA_GUADELOUPE = "America/Guadeloupe"
    AMERICA_GUATEMALA = "America/Guatemala"
    AMERICA_GUAYAQUIL = "America/Guayaquil"
    AMERICA_GUYANA = "America/Guyana"
    AMERICA_HALIFAX = "America/Halifax"
    AMERICA_HAVANA = "America/Havana"
    AMERICA_HERMOSILLO = "America/Hermosillo"
    AMERICA_INDIANA_INDIANAPOLIS = "America/Indiana/Indianapolis"
    AMERICA_INDIANA_KNOX = "America/Indiana/Knox"
    AMERICA_INDIANA_MARENGO = "America/Indiana/Marengo"
    AMERICA_INDIANA_PETERSBURG = "America/Indiana/Petersburg"
    AMERICA_INDIANA_TELL_CITY = "America/Indiana/Tell_City"
    AMERICA_INDIANA_VEVAY = "America/Indiana/Vevay"
    AMERICA_INDIANA_VINCENNES = "America/Indiana/Vincennes"
    AMERICA_INDIANA_WINAMAC = "America/Indiana/Winamac"
    AMERICA_INDIANAPOLIS = "America/Indianapolis"
    AMERICA_INUVIK = "America/Inuvik"
    AMERICA_IQALUIT = "America/Iqaluit"
    AMERICA_JAMAICA = "America/Jamaica"
    AMERICA_JUJUY = "America/Jujuy"
    AMERICA_JUNEAU = "America/Juneau"
    AMERICA_KENTUCKY_LOUISVILLE = "America/Kentucky/Louisville"
    AMERICA_KENTUCKY_MONTICELLO = "America/Kentucky/Monticello"
    AMERICA_KNOX_IN = "America/Knox_IN"
    AMERICA_KRALENDIJK = "America/Kralendijk"
    AMERICA_LA_PAZ = "America/La_Paz"
    AMERICA_LIMA = "America/Lima"
    AMERICA_LOS_ANGELES = "America/Los_Angeles"
    AMERICA_LOUISVILLE = "America/Louisville"
    AMERICA_LOWER_PRINCES = "America/Lower_Princes"
    AMERICA_MACEIO = "America/Maceio"
    AMERICA_MANAGUA = "America/Managua"
    AMERICA_MANAUS = "America/Manaus"
    AMERICA_MARIGOT = "America/Marigot"
    AMERICA_MARTINIQUE = "America/Martinique"
    AMERICA_MATAMOROS = "America/Matamoros"
    AMERICA_MAZATLAN = "America/Mazatlan"
    AMERICA_MENDOZA = "America/Mendoza"
    AMERICA_MENOMINEE = "America/Menominee"
    AMERICA_MERIDA = "America/Merida"
    AMERICA_METLAKATLA = "America/Metlakatla"
    AMERICA_MEXICO_CITY = "America/Mexico_City"
    AMERICA_MIQUELON = "America/Miquelon"
    AMERICA_MONCTON = "America/Moncton"
    AMERICA_MONTERREY = "America/Monterrey"
    AMERICA_MONTEVIDEO = "America/Montevideo"
    AMERICA_MONTREAL = "America/Montreal"
    AMERICA_MONTSERRAT = "America/Montserrat"
    AMERICA_NASSAU = "America/Nassau"
    AMERICA_NEW_YORK = "America/New_York"
    AMERICA_NIPIGON = "America/Nipigon"
    AMERICA_NOME = "America/Nome"
    AMERICA_NORONHA = "America/Noronha"
    AMERICA_NORTH_DAKOTA_BEULAH = "America/North_Dakota/Beulah"
    AMERICA_NORTH_DAKOTA_CENTER = "America/North_Dakota/Center"
    AMERICA_NORTH_DAKOTA_NEW_SALEM = "America/North_Dakota/New_Salem"
    AMERICA_NUUK = "America/Nuuk"
    AMERICA_OJINAGA = "America/Ojinaga"
    AMERICA_PANAMA = "America/Panama"
    AMERICA_PANGNIRTUNG = "America/Pangnirtung"
    AMERICA_PARAMARIBO = "America/Paramaribo"
    AMERICA_PHOENIX = "America/Phoenix"
    AMERICA_PORT_AU_PRINCE = "America/Port-au-Prince"
    AMERICA_PORT_OF_SPAIN = "America/Port_of_Spain"
    AMERICA_PORTO_ACRE = "America/Porto_Acre"
    AMERICA_PORTO_VELHO = "America/Porto_Velho"
    AMERICA_PUERTO_RICO = "America/Puerto_Rico"
    AMERICA_PUNTA_ARENAS = "America/Punta_Arenas"
    AMERICA_RAINY_RIVER = "America/Rainy_River"
    AMERICA_RANKIN_INLET = "America/Rankin_Inlet"
    AMERICA_RECIFE = "America/Recife"
    AMERICA_REGINA = "America/Regina"
    AMERICA_RESOLUTE = "America/Resolute"
    AMERICA_RIO_BRANCO = "America/Rio_Branco"
    AMERICA_ROSARIO = "America/Rosario"
    AMERICA_SANTA_ISABEL = "America/Santa_Isabel"
    AMERICA_SANTAREM = "America/Santarem"
    AMERICA_SANTIAGO = "America/Santiago"
    AMERICA_SANTO_DOMINGO = "America/Santo_Domingo"
    AMERICA_SAO_PAULO = "America/Sao_Paulo"
    AMERICA_SCORESBYSUND = "America/Scoresbysund"
    AMERICA_SHIPROCK = "America/Shiprock"
    AMERICA_SITKA = "America/Sitka"
    AMERICA_ST_BARTHELEMY = "America/St_Barthelemy"
    AMERICA_ST_JOHNS = "America/St_Johns"
    AMERICA_ST_KITTS = "America/St_Kitts"
    AMERICA_ST_LUCIA = "America/St_Lucia"
    AMERICA_ST_THOMAS = "America/St_Thomas"
    AMERICA_ST_VINCENT = "America/St_Vincent"
    AMERICA_SWIFT_CURRENT = "America/Swift_Current"
    AMERICA_TEGUCIGALPA = "America/Tegucigalpa"
    AMERICA_THULE = "America/Thule"
    AMERICA_THUNDER_BAY = "America/Thunder_Bay"
    AMERICA_TIJUANA = "America/Tijuana"
    AMERICA_TORONTO = "America/Toronto"
    AMERICA_TORTOLA = "America/Tortola"
    AMERICA_VANCOUVER = "America/Vancouver"
    AMERICA_VIRGIN = "America/Virgin"
    AMERICA_WHITEHORSE = "America/Whitehorse"
    AMERICA_WINNIPEG = "America/Winnipeg"
    AMERICA_YAKUTAT = "America/Yakutat"
    AMERICA_YELLOWKNIFE = "America/Yellowknife"
    ANTARCTICA_CASEY = "Antarctica/Casey"
    ANTARCTICA_DAVIS = "Antarctica/Davis"
    ANTARCTICA_DUMONT_D_URVILLE = "Antarctica/DumontDUrville"
    ANTARCTICA_MACQUARIE = "Antarctica/Macquarie"
    ANTARCTICA_MAWSON = "Antarctica/Mawson"
    ANTARCTICA_MC_MURDO = "Antarctica/McMurdo"
    ANTARCTICA_PALMER = "Antarctica/Palmer"
    ANTARCTICA_ROTHERA = "Antarctica/Rothera"
    ANTARCTICA_SOUTH_POLE = "Antarctica/South_Pole"
    ANTARCTICA_SYOWA = "Antarctica/Syowa"
    ANTARCTICA_TROLL = "Antarctica/Troll"
    ANTARCTICA_VOSTOK = "Antarctica/Vostok"
    ARCTIC_LONGYEARBYEN = "Arctic/Longyearbyen"
    ASIA_ADEN = "Asia/Aden"
    ASIA_ALMATY = "Asia/Almaty"
    ASIA_AMMAN = "Asia/Amman"
    ASIA_ANADYR = "Asia/Anadyr"
    ASIA_AQTAU = "Asia/Aqtau"
    ASIA_AQTOBE = "Asia/Aqtobe"
    ASIA_ASHGABAT = "Asia/Ashgabat"
    ASIA_ASHKHABAD = "Asia/Ashkhabad"
    ASIA_ATYRAU = "Asia/Atyrau"
    ASIA_BAGHDAD = "Asia/Baghdad"
    ASIA_BAHRAIN = "Asia/Bahrain"
    ASIA_BAKU = "Asia/Baku"
    ASIA_BANGKOK = "Asia/Bangkok"
    ASIA_BARNAUL = "Asia/Barnaul"
    ASIA_BEIRUT = "Asia/Beirut"
    ASIA_BISHKEK = "Asia/Bishkek"
    ASIA_BRUNEI = "Asia/Brunei"
    ASIA_CALCUTTA = "Asia/Calcutta"
    ASIA_CHITA = "Asia/Chita"
    ASIA_CHOIBALSAN = "Asia/Choibalsan"
    ASIA_CHONGQING = "Asia/Chongqing"
    ASIA_CHUNGKING = "Asia/Chungking"
    ASIA_COLOMBO = "Asia/Colombo"
    ASIA_DACCA = "Asia/Dacca"
    ASIA_DAMASCUS = "Asia/Damascus"
    ASIA_DHAKA = "Asia/Dhaka"
    ASIA_DILI = "Asia/Dili"
    ASIA_DUBAI = "Asia/Dubai"
    ASIA_DUSHANBE = "Asia/Dushanbe"
    ASIA_FAMAGUSTA = "Asia/Famagusta"
    ASIA_GAZA = "Asia/Gaza"
    ASIA_HARBIN = "Asia/Harbin"
    ASIA_HEBRON = "Asia/Hebron"
    ASIA_HO_CHI_MINH = "Asia/Ho_Chi_Minh"
    ASIA_HONG_KONG = "Asia/Hong_Kong"
    ASIA_HOVD = "Asia/Hovd"
    ASIA_IRKUTSK = "Asia/Irkutsk"
    ASIA_ISTANBUL = "Asia/Istanbul"
    ASIA_JAKARTA = "Asia/Jakarta"
    ASIA_JAYAPURA = "Asia/Jayapura"
    ASIA_JERUSALEM = "Asia/Jerusalem"
    ASIA_KABUL = "Asia/Kabul"
    ASIA_KAMCHATKA = "Asia/Kamchatka"
    ASIA_KARACHI = "Asia/Karachi"
    ASIA_KASHGAR = "Asia/Kashgar"
    ASIA_KATHMANDU = "Asia/Kathmandu"
    ASIA_KATMANDU = "Asia/Katmandu"
    ASIA_KHANDYGA = "Asia/Khandyga"
    ASIA_KOLKATA = "Asia/Kolkata"
    ASIA_KRASNOYARSK = "Asia/Krasnoyarsk"
    ASIA_KUALA_LUMPUR = "Asia/Kuala_Lumpur"
    ASIA_KUCHING = "Asia/Kuching"
    ASIA_KUWAIT = "Asia/Kuwait"
    ASIA_MACAO = "Asia/Macao"
    ASIA_MACAU = "Asia/Macau"
    ASIA_MAGADAN = "Asia/Magadan"
    ASIA_MAKASSAR = "Asia/Makassar"
    ASIA_MANILA = "Asia/Manila"
    ASIA_MUSCAT = "Asia/Muscat"
    ASIA_NICOSIA = "Asia/Nicosia"
    ASIA_NOVOKUZNETSK = "Asia/Novokuznetsk"
    ASIA_NOVOSIBIRSK = "Asia/Novosibirsk"
    ASIA_OMSK = "Asia/Omsk"
    ASIA_ORAL = "Asia/Oral"
    ASIA_PHNOM_PENH = "Asia/Phnom_Penh"
    ASIA_PONTIANAK = "Asia/Pontianak"
    ASIA_PYONGYANG = "Asia/Pyongyang"
    ASIA_QATAR = "Asia/Qatar"
    ASIA_QOSTANAY = "Asia/Qostanay"
    ASIA_QYZYLORDA = "Asia/Qyzylorda"
    ASIA_RANGOON = "Asia/Rangoon"
    ASIA_RIYADH = "Asia/Riyadh"
    ASIA_SAIGON = "Asia/Saigon"
    ASIA_SAKHALIN = "Asia/Sakhalin"
    ASIA_SAMARKAND = "Asia/Samarkand"
    ASIA_SEOUL = "Asia/Seoul"
    ASIA_SHANGHAI = "Asia/Shanghai"
    ASIA_SINGAPORE = "Asia/Singapore"
    ASIA_SREDNEKOLYMSK = "Asia/Srednekolymsk"
    ASIA_TAIPEI = "Asia/Taipei"
    ASIA_TASHKENT = "Asia/Tashkent"
    ASIA_TBILISI = "Asia/Tbilisi"
    ASIA_TEHRAN = "Asia/Tehran"
    ASIA_TEL_AVIV = "Asia/Tel_Aviv"
    ASIA_THIMBU = "Asia/Thimbu"
    ASIA_THIMPHU = "Asia/Thimphu"
    ASIA_TOKYO = "Asia/Tokyo"
    ASIA_TOMSK = "Asia/Tomsk"
    ASIA_UJUNG_PANDANG = "Asia/Ujung_Pandang"
    ASIA_ULAANBAATAR = "Asia/Ulaanbaatar"
    ASIA_ULAN_BATOR = "Asia/Ulan_Bator"
    ASIA_URUMQI = "Asia/Urumqi"
    ASIA_UST_NERA = "Asia/Ust-Nera"
    ASIA_VIENTIANE = "Asia/Vientiane"
    ASIA_VLADIVOSTOK = "Asia/Vladivostok"
    ASIA_YAKUTSK = "Asia/Yakutsk"
    ASIA_YANGON = "Asia/Yangon"
    ASIA_YEKATERINBURG = "Asia/Yekaterinburg"
    ASIA_YEREVAN = "Asia/Yerevan"
    ATLANTIC_AZORES = "Atlantic/Azores"
    ATLANTIC_BERMUDA = "Atlantic/Bermuda"
    ATLANTIC_CANARY = "Atlantic/Canary"
    ATLANTIC_CAPE_VERDE = "Atlantic/Cape_Verde"
    ATLANTIC_FAEROE = "Atlantic/Faeroe"
    ATLANTIC_FAROE = "Atlantic/Faroe"
    ATLANTIC_JAN_MAYEN = "Atlantic/Jan_Mayen"
    ATLANTIC_MADEIRA = "Atlantic/Madeira"
    ATLANTIC_REYKJAVIK = "Atlantic/Reykjavik"
    ATLANTIC_SOUTH_GEORGIA = "Atlantic/South_Georgia"
    ATLANTIC_ST_HELENA = "Atlantic/St_Helena"
    ATLANTIC_STANLEY = "Atlantic/Stanley"
    AUSTRALIA_ACT = "Australia/ACT"
    AUSTRALIA_ADELAIDE = "Australia/Adelaide"
    AUSTRALIA_BRISBANE = "Australia/Brisbane"
    AUSTRALIA_BROKEN_HILL = "Australia/Broken_Hill"
    AUSTRALIA_CANBERRA = "Australia/Canberra"
    AUSTRALIA_CURRIE = "Australia/Currie"
    AUSTRALIA_DARWIN = "Australia/Darwin"
    AUSTRALIA_EUCLA = "Australia/Eucla"
    AUSTRALIA_HOBART = "Australia/Hobart"
    AUSTRALIA_LHI = "Australia/LHI"
    AUSTRALIA_LINDEMAN = "Australia/Lindeman"
    AUSTRALIA_LORD_HOWE = "Australia/Lord_Howe"
    AUSTRALIA_MELBOURNE = "Australia/Melbourne"
    AUSTRALIA_NSW = "Australia/NSW"
    AUSTRALIA_NORTH = "Australia/North"
    AUSTRALIA_PERTH = "Australia/Perth"
    AUSTRALIA_QUEENSLAND = "Australia/Queensland"
    AUSTRALIA_SOUTH = "Australia/South"
    AUSTRALIA_SYDNEY = "Australia/Sydney"
    AUSTRALIA_TASMANIA = "Australia/Tasmania"
    AUSTRALIA_VICTORIA = "Australia/Victoria"
    AUSTRALIA_WEST = "Australia/West"
    AUSTRALIA_YANCOWINNA = "Australia/Yancowinna"
    BRAZIL_ACRE = "Brazil/Acre"
    BRAZIL_DE_NORONHA = "Brazil/DeNoronha"
    BRAZIL_EAST = "Brazil/East"
    BRAZIL_WEST = "Brazil/West"
    CET = "CET"
    CST6_CDT = "CST6CDT"
    CANADA_ATLANTIC = "Canada/Atlantic"
    CANADA_CENTRAL = "Canada/Central"
    CANADA_EASTERN = "Canada/Eastern"
    CANADA_MOUNTAIN = "Canada/Mountain"
    CANADA_NEWFOUNDLAND = "Canada/Newfoundland"
    CANADA_PACIFIC = "Canada/Pacific"
    CANADA_SASKATCHEWAN = "Canada/Saskatchewan"
    CANADA_YUKON = "Canada/Yukon"
    CHILE_CONTINENTAL = "Chile/Continental"
    CHILE_EASTER_ISLAND = "Chile/EasterIsland"
    CUBA = "Cuba"
    EET = "EET"
    EST = "EST"
    EST5_EDT = "EST5EDT"
    EGYPT = "Egypt"
    EIRE = "Eire"
    ETC_GMT = "Etc/GMT"
    ETC_GMT_0 = "Etc/GMT+0"
    ETC_GMT_1 = "Etc/GMT+1"
    ETC_GMT_10 = "Etc/GMT+10"
    ETC_GMT_11 = "Etc/GMT+11"
    ETC_GMT_12 = "Etc/GMT+12"
    ETC_GMT_2 = "Etc/GMT+2"
    ETC_GMT_3 = "Etc/GMT+3"
    ETC_GMT_4 = "Etc/GMT+4"
    ETC_GMT_5 = "Etc/GMT+5"
    ETC_GMT_6 = "Etc/GMT+6"
    ETC_GMT_7 = "Etc/GMT+7"
    ETC_GMT_8 = "Etc/GMT+8"
    ETC_GMT_9 = "Etc/GMT+9"
    etc_gmt_0_1 = "Etc/GMT-0"
    etc_gmt_1_1 = "Etc/GMT-1"
    etc_gmt_10_1 = "Etc/GMT-10"
    etc_gmt_11_1 = "Etc/GMT-11"
    etc_gmt_12_1 = "Etc/GMT-12"
    ETC_GMT_13 = "Etc/GMT-13"
    ETC_GMT_14 = "Etc/GMT-14"
    etc_gmt_2_1 = "Etc/GMT-2"
    etc_gmt_3_1 = "Etc/GMT-3"
    etc_gmt_4_1 = "Etc/GMT-4"
    etc_gmt_5_1 = "Etc/GMT-5"
    etc_gmt_6_1 = "Etc/GMT-6"
    etc_gmt_7_1 = "Etc/GMT-7"
    etc_gmt_8_1 = "Etc/GMT-8"
    etc_gmt_9_1 = "Etc/GMT-9"
    ETC_GMT0 = "Etc/GMT0"
    ETC_GREENWICH = "Etc/Greenwich"
    ETC_UCT = "Etc/UCT"
    ETC_UTC = "Etc/UTC"
    ETC_UNIVERSAL = "Etc/Universal"
    ETC_ZULU = "Etc/Zulu"
    EUROPE_AMSTERDAM = "Europe/Amsterdam"
    EUROPE_ANDORRA = "Europe/Andorra"
    EUROPE_ASTRAKHAN = "Europe/Astrakhan"
    EUROPE_ATHENS = "Europe/Athens"
    EUROPE_BELFAST = "Europe/Belfast"
    EUROPE_BELGRADE = "Europe/Belgrade"
    EUROPE_BERLIN = "Europe/Berlin"
    EUROPE_BRATISLAVA = "Europe/Bratislava"
    EUROPE_BRUSSELS = "Europe/Brussels"
    EUROPE_BUCHAREST = "Europe/Bucharest"
    EUROPE_BUDAPEST = "Europe/Budapest"
    EUROPE_BUSINGEN = "Europe/Busingen"
    EUROPE_CHISINAU = "Europe/Chisinau"
    EUROPE_COPENHAGEN = "Europe/Copenhagen"
    EUROPE_DUBLIN = "Europe/Dublin"
    EUROPE_GIBRALTAR = "Europe/Gibraltar"
    EUROPE_GUERNSEY = "Europe/Guernsey"
    EUROPE_HELSINKI = "Europe/Helsinki"
    EUROPE_ISLE_OF_MAN = "Europe/Isle_of_Man"
    EUROPE_ISTANBUL = "Europe/Istanbul"
    EUROPE_JERSEY = "Europe/Jersey"
    EUROPE_KALININGRAD = "Europe/Kaliningrad"
    EUROPE_KIEV = "Europe/Kiev"
    EUROPE_KIROV = "Europe/Kirov"
    EUROPE_KYIV = "Europe/Kyiv"
    EUROPE_LISBON = "Europe/Lisbon"
    EUROPE_LJUBLJANA = "Europe/Ljubljana"
    EUROPE_LONDON = "Europe/London"
    EUROPE_LUXEMBOURG = "Europe/Luxembourg"
    EUROPE_MADRID = "Europe/Madrid"
    EUROPE_MALTA = "Europe/Malta"
    EUROPE_MARIEHAMN = "Europe/Mariehamn"
    EUROPE_MINSK = "Europe/Minsk"
    EUROPE_MONACO = "Europe/Monaco"
    EUROPE_MOSCOW = "Europe/Moscow"
    EUROPE_NICOSIA = "Europe/Nicosia"
    EUROPE_OSLO = "Europe/Oslo"
    EUROPE_PARIS = "Europe/Paris"
    EUROPE_PODGORICA = "Europe/Podgorica"
    EUROPE_PRAGUE = "Europe/Prague"
    EUROPE_RIGA = "Europe/Riga"
    EUROPE_ROME = "Europe/Rome"
    EUROPE_SAMARA = "Europe/Samara"
    EUROPE_SAN_MARINO = "Europe/San_Marino"
    EUROPE_SARAJEVO = "Europe/Sarajevo"
    EUROPE_SARATOV = "Europe/Saratov"
    EUROPE_SIMFEROPOL = "Europe/Simferopol"
    EUROPE_SKOPJE = "Europe/Skopje"
    EUROPE_SOFIA = "Europe/Sofia"
    EUROPE_STOCKHOLM = "Europe/Stockholm"
    EUROPE_TALLINN = "Europe/Tallinn"
    EUROPE_TIRANE = "Europe/Tirane"
    EUROPE_TIRASPOL = "Europe/Tiraspol"
    EUROPE_ULYANOVSK = "Europe/Ulyanovsk"
    EUROPE_UZHGOROD = "Europe/Uzhgorod"
    EUROPE_VADUZ = "Europe/Vaduz"
    EUROPE_VATICAN = "Europe/Vatican"
    EUROPE_VIENNA = "Europe/Vienna"
    EUROPE_VILNIUS = "Europe/Vilnius"
    EUROPE_VOLGOGRAD = "Europe/Volgograd"
    EUROPE_WARSAW = "Europe/Warsaw"
    EUROPE_ZAGREB = "Europe/Zagreb"
    EUROPE_ZAPOROZHYE = "Europe/Zaporozhye"
    EUROPE_ZURICH = "Europe/Zurich"
    FACTORY = "Factory"
    GB = "GB"
    GB_EIRE = "GB-Eire"
    GMT = "GMT"
    GMT_0 = "GMT+0"
    gmt_0_1 = "GMT-0"
    GMT0 = "GMT0"
    GREENWICH = "Greenwich"
    HST = "HST"
    HONGKONG = "Hongkong"
    ICELAND = "Iceland"
    INDIAN_ANTANANARIVO = "Indian/Antananarivo"
    INDIAN_CHAGOS = "Indian/Chagos"
    INDIAN_CHRISTMAS = "Indian/Christmas"
    INDIAN_COCOS = "Indian/Cocos"
    INDIAN_COMORO = "Indian/Comoro"
    INDIAN_KERGUELEN = "Indian/Kerguelen"
    INDIAN_MAHE = "Indian/Mahe"
    INDIAN_MALDIVES = "Indian/Maldives"
    INDIAN_MAURITIUS = "Indian/Mauritius"
    INDIAN_MAYOTTE = "Indian/Mayotte"
    INDIAN_REUNION = "Indian/Reunion"
    IRAN = "Iran"
    ISRAEL = "Israel"
    JAMAICA = "Jamaica"
    JAPAN = "Japan"
    KWAJALEIN = "Kwajalein"
    LIBYA = "Libya"
    MET = "MET"
    MST = "MST"
    MST7_MDT = "MST7MDT"
    MEXICO_BAJA_NORTE = "Mexico/BajaNorte"
    MEXICO_BAJA_SUR = "Mexico/BajaSur"
    MEXICO_GENERAL = "Mexico/General"
    NZ = "NZ"
    NZ_CHAT = "NZ-CHAT"
    NAVAJO = "Navajo"
    PRC = "PRC"
    PST8_PDT = "PST8PDT"
    PACIFIC_APIA = "Pacific/Apia"
    PACIFIC_AUCKLAND = "Pacific/Auckland"
    PACIFIC_BOUGAINVILLE = "Pacific/Bougainville"
    PACIFIC_CHATHAM = "Pacific/Chatham"
    PACIFIC_CHUUK = "Pacific/Chuuk"
    PACIFIC_EASTER = "Pacific/Easter"
    PACIFIC_EFATE = "Pacific/Efate"
    PACIFIC_ENDERBURY = "Pacific/Enderbury"
    PACIFIC_FAKAOFO = "Pacific/Fakaofo"
    PACIFIC_FIJI = "Pacific/Fiji"
    PACIFIC_FUNAFUTI = "Pacific/Funafuti"
    PACIFIC_GALAPAGOS = "Pacific/Galapagos"
    PACIFIC_GAMBIER = "Pacific/Gambier"
    PACIFIC_GUADALCANAL = "Pacific/Guadalcanal"
    PACIFIC_GUAM = "Pacific/Guam"
    PACIFIC_HONOLULU = "Pacific/Honolulu"
    PACIFIC_JOHNSTON = "Pacific/Johnston"
    PACIFIC_KANTON = "Pacific/Kanton"
    PACIFIC_KIRITIMATI = "Pacific/Kiritimati"
    PACIFIC_KOSRAE = "Pacific/Kosrae"
    PACIFIC_KWAJALEIN = "Pacific/Kwajalein"
    PACIFIC_MAJURO = "Pacific/Majuro"
    PACIFIC_MARQUESAS = "Pacific/Marquesas"
    PACIFIC_MIDWAY = "Pacific/Midway"
    PACIFIC_NAURU = "Pacific/Nauru"
    PACIFIC_NIUE = "Pacific/Niue"
    PACIFIC_NORFOLK = "Pacific/Norfolk"
    PACIFIC_NOUMEA = "Pacific/Noumea"
    PACIFIC_PAGO_PAGO = "Pacific/Pago_Pago"
    PACIFIC_PALAU = "Pacific/Palau"
    PACIFIC_PITCAIRN = "Pacific/Pitcairn"
    PACIFIC_POHNPEI = "Pacific/Pohnpei"
    PACIFIC_PONAPE = "Pacific/Ponape"
    PACIFIC_PORT_MORESBY = "Pacific/Port_Moresby"
    PACIFIC_RAROTONGA = "Pacific/Rarotonga"
    PACIFIC_SAIPAN = "Pacific/Saipan"
    PACIFIC_SAMOA = "Pacific/Samoa"
    PACIFIC_TAHITI = "Pacific/Tahiti"
    PACIFIC_TARAWA = "Pacific/Tarawa"
    PACIFIC_TONGATAPU = "Pacific/Tongatapu"
    PACIFIC_TRUK = "Pacific/Truk"
    PACIFIC_WAKE = "Pacific/Wake"
    PACIFIC_WALLIS = "Pacific/Wallis"
    PACIFIC_YAP = "Pacific/Yap"
    POLAND = "Poland"
    PORTUGAL = "Portugal"
    ROC = "ROC"
    ROK = "ROK"
    SINGAPORE = "Singapore"
    TURKEY = "Turkey"
    UCT = "UCT"
    US_ALASKA = "US/Alaska"
    US_ALEUTIAN = "US/Aleutian"
    US_ARIZONA = "US/Arizona"
    US_CENTRAL = "US/Central"
    US_EAST_INDIANA = "US/East-Indiana"
    US_EASTERN = "US/Eastern"
    US_HAWAII = "US/Hawaii"
    US_INDIANA_STARKE = "US/Indiana-Starke"
    US_MICHIGAN = "US/Michigan"
    US_MOUNTAIN = "US/Mountain"
    US_PACIFIC = "US/Pacific"
    US_SAMOA = "US/Samoa"
    UTC = "UTC"
    UNIVERSAL = "Universal"
    W_SU = "W-SU"
    WET = "WET"
    ZULU = "Zulu"
    LOCALTIME = "localtime"


class Workhour(RootModel[list[time]]):
    root: Annotated[list[time], Field(max_length=2)]


class FuelUsedSource(RootModel[FuelUsedSourceEnum]):
    root: FuelUsedSourceEnum


class Vehicle(BaseModel):
    id: UUID | None = None
    url: AnyUrl | None = None
    account: AnyUrl | None = None
    secondary_accounts: list[AnyUrl] | None = None
    country: str | None = None
    registration: str | None = None
    name: Annotated[str | None, Field(max_length=64)] = ""
    name_display: str | None = None
    active: bool | None = None
    accountable_user: AnyUrl | None = None
    driver: AnyUrl | None = None
    vehicle_groups: list[AnyUrl] | None = None
    workhours: Annotated[
        list[Workhour] | None, Field(max_length=7, title="Work hours per day")
    ] = None
    error_state_threshold: str | None = None
    fuel_events_enabled: bool | None = None
    fuel_used_source: FuelUsedSource | None = None
    """
    Which data source should be used in the main fuel used field.

    * `not_set` - Not set
    * `fuel_level` - Fuel level
    * `total_fuel_used` - Total fuel used
    """
    total_distance_enabled: bool | None = None
    total_engine_time_enabled: bool | None = None
    eco_score_enabled: bool | None = None
    last_activity_enabled: bool | None = None
    """
    Should the last activity info be used in the web/mobile apps to display vehicle state
    """
    country_split_enabled: bool | None = None
    daily_split_times_enabled: bool | None = None
    hide_private_trips: bool | None = None
    history_optimization_enabled: bool | None = None
    """
    Should the vehicle history data be optimized in the API for playback and integrations?
    """
    switched_by_ignition: bool | None = None
    average_fuel_consumption: Decimal | None = None
    """
    L/100km
    Note: OpenAPI spec incorrectly uses pattern constraint on decimal type.
    """
    hourly_fuel_consumption: Decimal | None = None
    """
    L/h
    Note: OpenAPI spec incorrectly uses pattern constraint on decimal type.
    """
    average_co2_emission: Annotated[
        int | None, Field(ge=-2147483648, le=2147483647)
    ] = None
    """
    g/km
    """
    hourly_co2_emission: Annotated[int | None, Field(ge=-2147483648, le=2147483647)] = (
        None
    )
    """
    g/h
    """
    trip_tariff: Decimal | None = None
    """
    cost/km
    Note: OpenAPI spec incorrectly uses pattern constraint on decimal type.
    """
    fuel_tank_capacities: list[int] | None = None
    fuel_tanked_thresholds: list[int] | None = None
    fuel_removed_thresholds: list[int] | None = None
    tachograph_enabled: bool | None = None
    auth_tachograph_card: Annotated[
        AnyUrl | None, Field(title="Tachograph card for authorization")
    ] = None
    tachograph_lock_card: Annotated[
        AnyUrl | None, Field(title="Company card used to lock the tachograph")
    ] = None
    tachograph_locked_at: AwareDatetime | None = None
    """
    Datetime when the tachograph was locked with the current locking card.
    """
    make: Annotated[str | None, Field(max_length=100)] = None
    model: Annotated[str | None, Field(max_length=100)] = None
    type: Annotated[str | None, Field(max_length=100)] = None
    vin: Annotated[str | None, Field(max_length=40)] = None
    color: Annotated[str | None, Field(max_length=20)] = None
    fuel_type: FuelTypeEnum | BlankEnum | NullEnum | None = None
    engine_displacement: Annotated[int | None, Field(ge=-2147483648, le=2147483647)] = (
        None
    )
    manufacturing_year: int | None = None
    first_registration_date: date | None = None
    leasing_start: date | None = None
    leasing_end: date | None = None
    leasing_period_mileage: Annotated[int | None, Field(ge=0, le=2147483647)] = None
    leasing_period_fee: Decimal | None = None
    """Note: OpenAPI spec incorrectly uses pattern constraint on decimal type."""
    additional_fields: Any | None = None


class Type(StrEnum):
    POINT = "Point"


class Location(BaseModel):
    """GeoJSON Point location."""

    type: Type | None = None
    coordinates: list[float] | None = None
    """GeoJSON coordinates [longitude, latitude]."""


class Trail(BaseModel):
    """Trail can be Point or LineString - accept flexible coordinates."""

    type: str | None = None
    coordinates: list | None = None


class Activity(RootModel[Activity3b5Enum]):
    root: Activity3b5Enum


class VehicleState(BaseModel):
    id: UUID | None = None
    vehicle: AnyUrl | None = None
    time: AwareDatetime | None = None
    location: Annotated[
        Location | None,
        Field(examples=[{"type": "Point", "coordinates": [24.76271, 59.416163]}]),
    ] = None
    """
    Geojson geometry object format
    """
    trail: Annotated[
        Trail | None,
        Field(examples=[{"type": "Point", "coordinates": [24.76271, 59.416163]}]),
    ] = None
    """
    Geojson geometry object format
    """
    eco_score: float
    activity: Activity | None = None
    activity_started_at: AwareDatetime | None = None
    activity_distance: float | None = None
    activity_engine_time: float | None = None
    received_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    interpolated_at: AwareDatetime | None = None
    streamed_at: AwareDatetime | None = None
    accelerator: float | None = None
    accumulated_distance: int | None = None
    accumulated_engine_time: float | None = None
    adblue_level_litres: float | None = None
    adblue_level_percent: float | None = None
    alarm: bool | None = None
    altitude: int | None = None
    ambient_air_temperature: float | None = None
    analog_input_1: int | None = None
    analog_input_2: int | None = None
    analog_input_3: int | None = None
    analog_input_4: int | None = None
    auxiliary_heater: bool | None = None
    axle_weight_1: int | None = None
    axle_weight_10: int | None = None
    axle_weight_11: int | None = None
    axle_weight_12: int | None = None
    axle_weight_13: int | None = None
    axle_weight_14: int | None = None
    axle_weight_15: int | None = None
    axle_weight_2: int | None = None
    axle_weight_3: int | None = None
    axle_weight_4: int | None = None
    axle_weight_5: int | None = None
    axle_weight_6: int | None = None
    axle_weight_7: int | None = None
    axle_weight_8: int | None = None
    axle_weight_9: int | None = None
    battery_level: int | None = None
    battery_voltage: float | None = None
    break_time: float | None = None
    can_fuel_level_percent: float | None = None
    charging_cable_connected: bool | None = None
    cruise_control: bool | None = None
    daily_driving_time: float | None = None
    daily_work_time: float | None = None
    digital_input_1: bool | None = None
    digital_input_2: bool | None = None
    digital_input_3: bool | None = None
    digital_input_4: bool | None = None
    digital_input_5: bool | None = None
    digital_input_6: bool | None = None
    digital_input_7: bool | None = None
    digital_input_8: bool | None = None
    digital_output_1: bool | None = None
    digital_output_2: bool | None = None
    digital_output_3: bool | None = None
    digital_output_4: bool | None = None
    door_states: str | None = None
    driver_1_card_id: str | None = None
    driver_1_card_present: bool | None = None
    driver_1_ibutton_id: str | None = None
    driver_1_rfid_id: str | None = None
    driver_1_time_state: int | None = None
    driver_1_working_state: int | None = None
    driver_2_card_id: str | None = None
    driver_2_card_present: bool | None = None
    driver_2_ibutton_id: str | None = None
    driver_2_rfid_id: str | None = None
    driver_2_time_state: int | None = None
    driver_2_working_state: int | None = None
    driving_time: float | None = None
    dtc_count: int | None = None
    eco_extreme_braking_events: int | None = None
    eco_harsh_acceleration_events: int | None = None
    eco_harsh_braking_events: int | None = None
    eco_harsh_cornering_events: int | None = None
    elect_battery_temperature: float | None = None
    elect_energy: int | None = None
    elect_recharge_distance: int | None = None
    elect_soc: int | None = None
    engine_absolute_load: float | None = None
    engine_coolant_temperature: float | None = None
    engine_oil_temperature: float | None = None
    engine_power: float | None = None
    engine_speed: float | None = None
    fuel_level: float | None = None
    fuel_level_1: float | None = None
    fuel_level_2: float | None = None
    fuel_level_3: float | None = None
    fuel_level_4: float | None = None
    fuel_level_5: float | None = None
    fuel_level_6: float | None = None
    fuel_level_ewma: float | None = None
    fuel_rate: float | None = None
    fuel_temperature: float | None = None
    fuel_temperature_1: float | None = None
    heading: int | None = None
    humidity_1: float | None = None
    humidity_2: float | None = None
    hv_battery_charging: bool | None = None
    ignition: bool | None = None
    intake_maf: float | None = None
    keypad_code: str | None = None
    notification: bool | None = None
    panic: bool | None = None
    satellites: int | None = None
    scooter_alarm: int | None = None
    scooter_buzzer: bool | None = None
    scooter_charging: bool | None = None
    scooter_error: int | None = None
    speed: int | None = None
    spreader_brine_dosage: float | None = None
    spreader_brine_spread: float | None = None
    spreader_solid_dosage: float | None = None
    spreader_solid_spread: float | None = None
    spreader_width: float | None = None
    starter_blocked: bool | None = None
    supply_voltage: float | None = None
    temperature_1: float | None = None
    temperature_2: float | None = None
    temperature_3: float | None = None
    temperature_4: float | None = None
    temperature_5: float | None = None
    temperature_6: float | None = None
    temperature_7: float | None = None
    temperature_8: float | None = None
    total_distance: int | None = None
    total_engine_time: float | None = None
    total_fuel_used: float | None = None
    two_weekly_driving_time: float | None = None
    two_weekly_work_time: float | None = None
    vehicle_locked: bool | None = None
    vehicle_weight: int | None = None
    weekly_driving_time: float | None = None
    weekly_work_time: float | None = None
    working_state: int | None = None
    work_time: float | None = None


class Account(BaseModel):
    id: UUID | None = None
    url: AnyUrl | None = None
    name: Annotated[str, Field(max_length=100)]
    reference: Annotated[
        int | None,
        Field(
            ge=-9223372036854775808, le=9223372036854775807, title="Reference number"
        ),
    ] = None
    registry_code: Annotated[str | None, Field(max_length=20)] = None
    vat_number: Annotated[
        str | None, Field(max_length=20, title="VAT identification number")
    ] = None
    default_language: DefaultLanguageEnum | BlankEnum | None = None
    """
    If blank Partner's default language will be chosen

    * `bg` - Bulgarian
    * `de` - German
    * `el` - Greek
    * `en` - English
    * `es` - Spanish
    * `et` - Estonian
    * `fi` - Finnish
    * `fr` - French
    * `lt` - Lithuanian
    * `lv` - Latvian
    * `nl` - Dutch
    * `pl` - Polish
    * `ru` - Russian
    """
    timezone: TimezoneEnum | BlankEnum | None = None
    """
    If blank Partner's timezone will be chosen

    * `Africa/Abidjan` - Africa/Abidjan
    * `Africa/Accra` - Africa/Accra
    * `Africa/Addis_Ababa` - Africa/Addis_Ababa
    * `Africa/Algiers` - Africa/Algiers
    * `Africa/Asmara` - Africa/Asmara
    * `Africa/Asmera` - Africa/Asmera
    * `Africa/Bamako` - Africa/Bamako
    * `Africa/Bangui` - Africa/Bangui
    * `Africa/Banjul` - Africa/Banjul
    * `Africa/Bissau` - Africa/Bissau
    * `Africa/Blantyre` - Africa/Blantyre
    * `Africa/Brazzaville` - Africa/Brazzaville
    * `Africa/Bujumbura` - Africa/Bujumbura
    * `Africa/Cairo` - Africa/Cairo
    * `Africa/Casablanca` - Africa/Casablanca
    * `Africa/Ceuta` - Africa/Ceuta
    * `Africa/Conakry` - Africa/Conakry
    * `Africa/Dakar` - Africa/Dakar
    * `Africa/Dar_es_Salaam` - Africa/Dar_es_Salaam
    * `Africa/Djibouti` - Africa/Djibouti
    * `Africa/Douala` - Africa/Douala
    * `Africa/El_Aaiun` - Africa/El_Aaiun
    * `Africa/Freetown` - Africa/Freetown
    * `Africa/Gaborone` - Africa/Gaborone
    * `Africa/Harare` - Africa/Harare
    * `Africa/Johannesburg` - Africa/Johannesburg
    * `Africa/Juba` - Africa/Juba
    * `Africa/Kampala` - Africa/Kampala
    * `Africa/Khartoum` - Africa/Khartoum
    * `Africa/Kigali` - Africa/Kigali
    * `Africa/Kinshasa` - Africa/Kinshasa
    * `Africa/Lagos` - Africa/Lagos
    * `Africa/Libreville` - Africa/Libreville
    * `Africa/Lome` - Africa/Lome
    * `Africa/Luanda` - Africa/Luanda
    * `Africa/Lubumbashi` - Africa/Lubumbashi
    * `Africa/Lusaka` - Africa/Lusaka
    * `Africa/Malabo` - Africa/Malabo
    * `Africa/Maputo` - Africa/Maputo
    * `Africa/Maseru` - Africa/Maseru
    * `Africa/Mbabane` - Africa/Mbabane
    * `Africa/Mogadishu` - Africa/Mogadishu
    * `Africa/Monrovia` - Africa/Monrovia
    * `Africa/Nairobi` - Africa/Nairobi
    * `Africa/Ndjamena` - Africa/Ndjamena
    * `Africa/Niamey` - Africa/Niamey
    * `Africa/Nouakchott` - Africa/Nouakchott
    * `Africa/Ouagadougou` - Africa/Ouagadougou
    * `Africa/Porto-Novo` - Africa/Porto-Novo
    * `Africa/Sao_Tome` - Africa/Sao_Tome
    * `Africa/Timbuktu` - Africa/Timbuktu
    * `Africa/Tripoli` - Africa/Tripoli
    * `Africa/Tunis` - Africa/Tunis
    * `Africa/Windhoek` - Africa/Windhoek
    * `America/Adak` - America/Adak
    * `America/Anchorage` - America/Anchorage
    * `America/Anguilla` - America/Anguilla
    * `America/Antigua` - America/Antigua
    * `America/Araguaina` - America/Araguaina
    * `America/Argentina/Buenos_Aires` - America/Argentina/Buenos_Aires
    * `America/Argentina/Catamarca` - America/Argentina/Catamarca
    * `America/Argentina/ComodRivadavia` - America/Argentina/ComodRivadavia
    * `America/Argentina/Cordoba` - America/Argentina/Cordoba
    * `America/Argentina/Jujuy` - America/Argentina/Jujuy
    * `America/Argentina/La_Rioja` - America/Argentina/La_Rioja
    * `America/Argentina/Mendoza` - America/Argentina/Mendoza
    * `America/Argentina/Rio_Gallegos` - America/Argentina/Rio_Gallegos
    * `America/Argentina/Salta` - America/Argentina/Salta
    * `America/Argentina/San_Juan` - America/Argentina/San_Juan
    * `America/Argentina/San_Luis` - America/Argentina/San_Luis
    * `America/Argentina/Tucuman` - America/Argentina/Tucuman
    * `America/Argentina/Ushuaia` - America/Argentina/Ushuaia
    * `America/Aruba` - America/Aruba
    * `America/Asuncion` - America/Asuncion
    * `America/Atikokan` - America/Atikokan
    * `America/Atka` - America/Atka
    * `America/Bahia` - America/Bahia
    * `America/Bahia_Banderas` - America/Bahia_Banderas
    * `America/Barbados` - America/Barbados
    * `America/Belem` - America/Belem
    * `America/Belize` - America/Belize
    * `America/Blanc-Sablon` - America/Blanc-Sablon
    * `America/Boa_Vista` - America/Boa_Vista
    * `America/Bogota` - America/Bogota
    * `America/Boise` - America/Boise
    * `America/Buenos_Aires` - America/Buenos_Aires
    * `America/Cambridge_Bay` - America/Cambridge_Bay
    * `America/Campo_Grande` - America/Campo_Grande
    * `America/Cancun` - America/Cancun
    * `America/Caracas` - America/Caracas
    * `America/Catamarca` - America/Catamarca
    * `America/Cayenne` - America/Cayenne
    * `America/Cayman` - America/Cayman
    * `America/Chicago` - America/Chicago
    * `America/Chihuahua` - America/Chihuahua
    * `America/Ciudad_Juarez` - America/Ciudad_Juarez
    * `America/Coral_Harbour` - America/Coral_Harbour
    * `America/Cordoba` - America/Cordoba
    * `America/Costa_Rica` - America/Costa_Rica
    * `America/Coyhaique` - America/Coyhaique
    * `America/Creston` - America/Creston
    * `America/Cuiaba` - America/Cuiaba
    * `America/Curacao` - America/Curacao
    * `America/Danmarkshavn` - America/Danmarkshavn
    * `America/Dawson` - America/Dawson
    * `America/Dawson_Creek` - America/Dawson_Creek
    * `America/Denver` - America/Denver
    * `America/Detroit` - America/Detroit
    * `America/Dominica` - America/Dominica
    * `America/Edmonton` - America/Edmonton
    * `America/Eirunepe` - America/Eirunepe
    * `America/El_Salvador` - America/El_Salvador
    * `America/Ensenada` - America/Ensenada
    * `America/Fort_Nelson` - America/Fort_Nelson
    * `America/Fort_Wayne` - America/Fort_Wayne
    * `America/Fortaleza` - America/Fortaleza
    * `America/Glace_Bay` - America/Glace_Bay
    * `America/Godthab` - America/Godthab
    * `America/Goose_Bay` - America/Goose_Bay
    * `America/Grand_Turk` - America/Grand_Turk
    * `America/Grenada` - America/Grenada
    * `America/Guadeloupe` - America/Guadeloupe
    * `America/Guatemala` - America/Guatemala
    * `America/Guayaquil` - America/Guayaquil
    * `America/Guyana` - America/Guyana
    * `America/Halifax` - America/Halifax
    * `America/Havana` - America/Havana
    * `America/Hermosillo` - America/Hermosillo
    * `America/Indiana/Indianapolis` - America/Indiana/Indianapolis
    * `America/Indiana/Knox` - America/Indiana/Knox
    * `America/Indiana/Marengo` - America/Indiana/Marengo
    * `America/Indiana/Petersburg` - America/Indiana/Petersburg
    * `America/Indiana/Tell_City` - America/Indiana/Tell_City
    * `America/Indiana/Vevay` - America/Indiana/Vevay
    * `America/Indiana/Vincennes` - America/Indiana/Vincennes
    * `America/Indiana/Winamac` - America/Indiana/Winamac
    * `America/Indianapolis` - America/Indianapolis
    * `America/Inuvik` - America/Inuvik
    * `America/Iqaluit` - America/Iqaluit
    * `America/Jamaica` - America/Jamaica
    * `America/Jujuy` - America/Jujuy
    * `America/Juneau` - America/Juneau
    * `America/Kentucky/Louisville` - America/Kentucky/Louisville
    * `America/Kentucky/Monticello` - America/Kentucky/Monticello
    * `America/Knox_IN` - America/Knox_IN
    * `America/Kralendijk` - America/Kralendijk
    * `America/La_Paz` - America/La_Paz
    * `America/Lima` - America/Lima
    * `America/Los_Angeles` - America/Los_Angeles
    * `America/Louisville` - America/Louisville
    * `America/Lower_Princes` - America/Lower_Princes
    * `America/Maceio` - America/Maceio
    * `America/Managua` - America/Managua
    * `America/Manaus` - America/Manaus
    * `America/Marigot` - America/Marigot
    * `America/Martinique` - America/Martinique
    * `America/Matamoros` - America/Matamoros
    * `America/Mazatlan` - America/Mazatlan
    * `America/Mendoza` - America/Mendoza
    * `America/Menominee` - America/Menominee
    * `America/Merida` - America/Merida
    * `America/Metlakatla` - America/Metlakatla
    * `America/Mexico_City` - America/Mexico_City
    * `America/Miquelon` - America/Miquelon
    * `America/Moncton` - America/Moncton
    * `America/Monterrey` - America/Monterrey
    * `America/Montevideo` - America/Montevideo
    * `America/Montreal` - America/Montreal
    * `America/Montserrat` - America/Montserrat
    * `America/Nassau` - America/Nassau
    * `America/New_York` - America/New_York
    * `America/Nipigon` - America/Nipigon
    * `America/Nome` - America/Nome
    * `America/Noronha` - America/Noronha
    * `America/North_Dakota/Beulah` - America/North_Dakota/Beulah
    * `America/North_Dakota/Center` - America/North_Dakota/Center
    * `America/North_Dakota/New_Salem` - America/North_Dakota/New_Salem
    * `America/Nuuk` - America/Nuuk
    * `America/Ojinaga` - America/Ojinaga
    * `America/Panama` - America/Panama
    * `America/Pangnirtung` - America/Pangnirtung
    * `America/Paramaribo` - America/Paramaribo
    * `America/Phoenix` - America/Phoenix
    * `America/Port-au-Prince` - America/Port-au-Prince
    * `America/Port_of_Spain` - America/Port_of_Spain
    * `America/Porto_Acre` - America/Porto_Acre
    * `America/Porto_Velho` - America/Porto_Velho
    * `America/Puerto_Rico` - America/Puerto_Rico
    * `America/Punta_Arenas` - America/Punta_Arenas
    * `America/Rainy_River` - America/Rainy_River
    * `America/Rankin_Inlet` - America/Rankin_Inlet
    * `America/Recife` - America/Recife
    * `America/Regina` - America/Regina
    * `America/Resolute` - America/Resolute
    * `America/Rio_Branco` - America/Rio_Branco
    * `America/Rosario` - America/Rosario
    * `America/Santa_Isabel` - America/Santa_Isabel
    * `America/Santarem` - America/Santarem
    * `America/Santiago` - America/Santiago
    * `America/Santo_Domingo` - America/Santo_Domingo
    * `America/Sao_Paulo` - America/Sao_Paulo
    * `America/Scoresbysund` - America/Scoresbysund
    * `America/Shiprock` - America/Shiprock
    * `America/Sitka` - America/Sitka
    * `America/St_Barthelemy` - America/St_Barthelemy
    * `America/St_Johns` - America/St_Johns
    * `America/St_Kitts` - America/St_Kitts
    * `America/St_Lucia` - America/St_Lucia
    * `America/St_Thomas` - America/St_Thomas
    * `America/St_Vincent` - America/St_Vincent
    * `America/Swift_Current` - America/Swift_Current
    * `America/Tegucigalpa` - America/Tegucigalpa
    * `America/Thule` - America/Thule
    * `America/Thunder_Bay` - America/Thunder_Bay
    * `America/Tijuana` - America/Tijuana
    * `America/Toronto` - America/Toronto
    * `America/Tortola` - America/Tortola
    * `America/Vancouver` - America/Vancouver
    * `America/Virgin` - America/Virgin
    * `America/Whitehorse` - America/Whitehorse
    * `America/Winnipeg` - America/Winnipeg
    * `America/Yakutat` - America/Yakutat
    * `America/Yellowknife` - America/Yellowknife
    * `Antarctica/Casey` - Antarctica/Casey
    * `Antarctica/Davis` - Antarctica/Davis
    * `Antarctica/DumontDUrville` - Antarctica/DumontDUrville
    * `Antarctica/Macquarie` - Antarctica/Macquarie
    * `Antarctica/Mawson` - Antarctica/Mawson
    * `Antarctica/McMurdo` - Antarctica/McMurdo
    * `Antarctica/Palmer` - Antarctica/Palmer
    * `Antarctica/Rothera` - Antarctica/Rothera
    * `Antarctica/South_Pole` - Antarctica/South_Pole
    * `Antarctica/Syowa` - Antarctica/Syowa
    * `Antarctica/Troll` - Antarctica/Troll
    * `Antarctica/Vostok` - Antarctica/Vostok
    * `Arctic/Longyearbyen` - Arctic/Longyearbyen
    * `Asia/Aden` - Asia/Aden
    * `Asia/Almaty` - Asia/Almaty
    * `Asia/Amman` - Asia/Amman
    * `Asia/Anadyr` - Asia/Anadyr
    * `Asia/Aqtau` - Asia/Aqtau
    * `Asia/Aqtobe` - Asia/Aqtobe
    * `Asia/Ashgabat` - Asia/Ashgabat
    * `Asia/Ashkhabad` - Asia/Ashkhabad
    * `Asia/Atyrau` - Asia/Atyrau
    * `Asia/Baghdad` - Asia/Baghdad
    * `Asia/Bahrain` - Asia/Bahrain
    * `Asia/Baku` - Asia/Baku
    * `Asia/Bangkok` - Asia/Bangkok
    * `Asia/Barnaul` - Asia/Barnaul
    * `Asia/Beirut` - Asia/Beirut
    * `Asia/Bishkek` - Asia/Bishkek
    * `Asia/Brunei` - Asia/Brunei
    * `Asia/Calcutta` - Asia/Calcutta
    * `Asia/Chita` - Asia/Chita
    * `Asia/Choibalsan` - Asia/Choibalsan
    * `Asia/Chongqing` - Asia/Chongqing
    * `Asia/Chungking` - Asia/Chungking
    * `Asia/Colombo` - Asia/Colombo
    * `Asia/Dacca` - Asia/Dacca
    * `Asia/Damascus` - Asia/Damascus
    * `Asia/Dhaka` - Asia/Dhaka
    * `Asia/Dili` - Asia/Dili
    * `Asia/Dubai` - Asia/Dubai
    * `Asia/Dushanbe` - Asia/Dushanbe
    * `Asia/Famagusta` - Asia/Famagusta
    * `Asia/Gaza` - Asia/Gaza
    * `Asia/Harbin` - Asia/Harbin
    * `Asia/Hebron` - Asia/Hebron
    * `Asia/Ho_Chi_Minh` - Asia/Ho_Chi_Minh
    * `Asia/Hong_Kong` - Asia/Hong_Kong
    * `Asia/Hovd` - Asia/Hovd
    * `Asia/Irkutsk` - Asia/Irkutsk
    * `Asia/Istanbul` - Asia/Istanbul
    * `Asia/Jakarta` - Asia/Jakarta
    * `Asia/Jayapura` - Asia/Jayapura
    * `Asia/Jerusalem` - Asia/Jerusalem
    * `Asia/Kabul` - Asia/Kabul
    * `Asia/Kamchatka` - Asia/Kamchatka
    * `Asia/Karachi` - Asia/Karachi
    * `Asia/Kashgar` - Asia/Kashgar
    * `Asia/Kathmandu` - Asia/Kathmandu
    * `Asia/Katmandu` - Asia/Katmandu
    * `Asia/Khandyga` - Asia/Khandyga
    * `Asia/Kolkata` - Asia/Kolkata
    * `Asia/Krasnoyarsk` - Asia/Krasnoyarsk
    * `Asia/Kuala_Lumpur` - Asia/Kuala_Lumpur
    * `Asia/Kuching` - Asia/Kuching
    * `Asia/Kuwait` - Asia/Kuwait
    * `Asia/Macao` - Asia/Macao
    * `Asia/Macau` - Asia/Macau
    * `Asia/Magadan` - Asia/Magadan
    * `Asia/Makassar` - Asia/Makassar
    * `Asia/Manila` - Asia/Manila
    * `Asia/Muscat` - Asia/Muscat
    * `Asia/Nicosia` - Asia/Nicosia
    * `Asia/Novokuznetsk` - Asia/Novokuznetsk
    * `Asia/Novosibirsk` - Asia/Novosibirsk
    * `Asia/Omsk` - Asia/Omsk
    * `Asia/Oral` - Asia/Oral
    * `Asia/Phnom_Penh` - Asia/Phnom_Penh
    * `Asia/Pontianak` - Asia/Pontianak
    * `Asia/Pyongyang` - Asia/Pyongyang
    * `Asia/Qatar` - Asia/Qatar
    * `Asia/Qostanay` - Asia/Qostanay
    * `Asia/Qyzylorda` - Asia/Qyzylorda
    * `Asia/Rangoon` - Asia/Rangoon
    * `Asia/Riyadh` - Asia/Riyadh
    * `Asia/Saigon` - Asia/Saigon
    * `Asia/Sakhalin` - Asia/Sakhalin
    * `Asia/Samarkand` - Asia/Samarkand
    * `Asia/Seoul` - Asia/Seoul
    * `Asia/Shanghai` - Asia/Shanghai
    * `Asia/Singapore` - Asia/Singapore
    * `Asia/Srednekolymsk` - Asia/Srednekolymsk
    * `Asia/Taipei` - Asia/Taipei
    * `Asia/Tashkent` - Asia/Tashkent
    * `Asia/Tbilisi` - Asia/Tbilisi
    * `Asia/Tehran` - Asia/Tehran
    * `Asia/Tel_Aviv` - Asia/Tel_Aviv
    * `Asia/Thimbu` - Asia/Thimbu
    * `Asia/Thimphu` - Asia/Thimphu
    * `Asia/Tokyo` - Asia/Tokyo
    * `Asia/Tomsk` - Asia/Tomsk
    * `Asia/Ujung_Pandang` - Asia/Ujung_Pandang
    * `Asia/Ulaanbaatar` - Asia/Ulaanbaatar
    * `Asia/Ulan_Bator` - Asia/Ulan_Bator
    * `Asia/Urumqi` - Asia/Urumqi
    * `Asia/Ust-Nera` - Asia/Ust-Nera
    * `Asia/Vientiane` - Asia/Vientiane
    * `Asia/Vladivostok` - Asia/Vladivostok
    * `Asia/Yakutsk` - Asia/Yakutsk
    * `Asia/Yangon` - Asia/Yangon
    * `Asia/Yekaterinburg` - Asia/Yekaterinburg
    * `Asia/Yerevan` - Asia/Yerevan
    * `Atlantic/Azores` - Atlantic/Azores
    * `Atlantic/Bermuda` - Atlantic/Bermuda
    * `Atlantic/Canary` - Atlantic/Canary
    * `Atlantic/Cape_Verde` - Atlantic/Cape_Verde
    * `Atlantic/Faeroe` - Atlantic/Faeroe
    * `Atlantic/Faroe` - Atlantic/Faroe
    * `Atlantic/Jan_Mayen` - Atlantic/Jan_Mayen
    * `Atlantic/Madeira` - Atlantic/Madeira
    * `Atlantic/Reykjavik` - Atlantic/Reykjavik
    * `Atlantic/South_Georgia` - Atlantic/South_Georgia
    * `Atlantic/St_Helena` - Atlantic/St_Helena
    * `Atlantic/Stanley` - Atlantic/Stanley
    * `Australia/ACT` - Australia/ACT
    * `Australia/Adelaide` - Australia/Adelaide
    * `Australia/Brisbane` - Australia/Brisbane
    * `Australia/Broken_Hill` - Australia/Broken_Hill
    * `Australia/Canberra` - Australia/Canberra
    * `Australia/Currie` - Australia/Currie
    * `Australia/Darwin` - Australia/Darwin
    * `Australia/Eucla` - Australia/Eucla
    * `Australia/Hobart` - Australia/Hobart
    * `Australia/LHI` - Australia/LHI
    * `Australia/Lindeman` - Australia/Lindeman
    * `Australia/Lord_Howe` - Australia/Lord_Howe
    * `Australia/Melbourne` - Australia/Melbourne
    * `Australia/NSW` - Australia/NSW
    * `Australia/North` - Australia/North
    * `Australia/Perth` - Australia/Perth
    * `Australia/Queensland` - Australia/Queensland
    * `Australia/South` - Australia/South
    * `Australia/Sydney` - Australia/Sydney
    * `Australia/Tasmania` - Australia/Tasmania
    * `Australia/Victoria` - Australia/Victoria
    * `Australia/West` - Australia/West
    * `Australia/Yancowinna` - Australia/Yancowinna
    * `Brazil/Acre` - Brazil/Acre
    * `Brazil/DeNoronha` - Brazil/DeNoronha
    * `Brazil/East` - Brazil/East
    * `Brazil/West` - Brazil/West
    * `CET` - CET
    * `CST6CDT` - CST6CDT
    * `Canada/Atlantic` - Canada/Atlantic
    * `Canada/Central` - Canada/Central
    * `Canada/Eastern` - Canada/Eastern
    * `Canada/Mountain` - Canada/Mountain
    * `Canada/Newfoundland` - Canada/Newfoundland
    * `Canada/Pacific` - Canada/Pacific
    * `Canada/Saskatchewan` - Canada/Saskatchewan
    * `Canada/Yukon` - Canada/Yukon
    * `Chile/Continental` - Chile/Continental
    * `Chile/EasterIsland` - Chile/EasterIsland
    * `Cuba` - Cuba
    * `EET` - EET
    * `EST` - EST
    * `EST5EDT` - EST5EDT
    * `Egypt` - Egypt
    * `Eire` - Eire
    * `Etc/GMT` - Etc/GMT
    * `Etc/GMT+0` - Etc/GMT+0
    * `Etc/GMT+1` - Etc/GMT+1
    * `Etc/GMT+10` - Etc/GMT+10
    * `Etc/GMT+11` - Etc/GMT+11
    * `Etc/GMT+12` - Etc/GMT+12
    * `Etc/GMT+2` - Etc/GMT+2
    * `Etc/GMT+3` - Etc/GMT+3
    * `Etc/GMT+4` - Etc/GMT+4
    * `Etc/GMT+5` - Etc/GMT+5
    * `Etc/GMT+6` - Etc/GMT+6
    * `Etc/GMT+7` - Etc/GMT+7
    * `Etc/GMT+8` - Etc/GMT+8
    * `Etc/GMT+9` - Etc/GMT+9
    * `Etc/GMT-0` - Etc/GMT-0
    * `Etc/GMT-1` - Etc/GMT-1
    * `Etc/GMT-10` - Etc/GMT-10
    * `Etc/GMT-11` - Etc/GMT-11
    * `Etc/GMT-12` - Etc/GMT-12
    * `Etc/GMT-13` - Etc/GMT-13
    * `Etc/GMT-14` - Etc/GMT-14
    * `Etc/GMT-2` - Etc/GMT-2
    * `Etc/GMT-3` - Etc/GMT-3
    * `Etc/GMT-4` - Etc/GMT-4
    * `Etc/GMT-5` - Etc/GMT-5
    * `Etc/GMT-6` - Etc/GMT-6
    * `Etc/GMT-7` - Etc/GMT-7
    * `Etc/GMT-8` - Etc/GMT-8
    * `Etc/GMT-9` - Etc/GMT-9
    * `Etc/GMT0` - Etc/GMT0
    * `Etc/Greenwich` - Etc/Greenwich
    * `Etc/UCT` - Etc/UCT
    * `Etc/UTC` - Etc/UTC
    * `Etc/Universal` - Etc/Universal
    * `Etc/Zulu` - Etc/Zulu
    * `Europe/Amsterdam` - Europe/Amsterdam
    * `Europe/Andorra` - Europe/Andorra
    * `Europe/Astrakhan` - Europe/Astrakhan
    * `Europe/Athens` - Europe/Athens
    * `Europe/Belfast` - Europe/Belfast
    * `Europe/Belgrade` - Europe/Belgrade
    * `Europe/Berlin` - Europe/Berlin
    * `Europe/Bratislava` - Europe/Bratislava
    * `Europe/Brussels` - Europe/Brussels
    * `Europe/Bucharest` - Europe/Bucharest
    * `Europe/Budapest` - Europe/Budapest
    * `Europe/Busingen` - Europe/Busingen
    * `Europe/Chisinau` - Europe/Chisinau
    * `Europe/Copenhagen` - Europe/Copenhagen
    * `Europe/Dublin` - Europe/Dublin
    * `Europe/Gibraltar` - Europe/Gibraltar
    * `Europe/Guernsey` - Europe/Guernsey
    * `Europe/Helsinki` - Europe/Helsinki
    * `Europe/Isle_of_Man` - Europe/Isle_of_Man
    * `Europe/Istanbul` - Europe/Istanbul
    * `Europe/Jersey` - Europe/Jersey
    * `Europe/Kaliningrad` - Europe/Kaliningrad
    * `Europe/Kiev` - Europe/Kiev
    * `Europe/Kirov` - Europe/Kirov
    * `Europe/Kyiv` - Europe/Kyiv
    * `Europe/Lisbon` - Europe/Lisbon
    * `Europe/Ljubljana` - Europe/Ljubljana
    * `Europe/London` - Europe/London
    * `Europe/Luxembourg` - Europe/Luxembourg
    * `Europe/Madrid` - Europe/Madrid
    * `Europe/Malta` - Europe/Malta
    * `Europe/Mariehamn` - Europe/Mariehamn
    * `Europe/Minsk` - Europe/Minsk
    * `Europe/Monaco` - Europe/Monaco
    * `Europe/Moscow` - Europe/Moscow
    * `Europe/Nicosia` - Europe/Nicosia
    * `Europe/Oslo` - Europe/Oslo
    * `Europe/Paris` - Europe/Paris
    * `Europe/Podgorica` - Europe/Podgorica
    * `Europe/Prague` - Europe/Prague
    * `Europe/Riga` - Europe/Riga
    * `Europe/Rome` - Europe/Rome
    * `Europe/Samara` - Europe/Samara
    * `Europe/San_Marino` - Europe/San_Marino
    * `Europe/Sarajevo` - Europe/Sarajevo
    * `Europe/Saratov` - Europe/Saratov
    * `Europe/Simferopol` - Europe/Simferopol
    * `Europe/Skopje` - Europe/Skopje
    * `Europe/Sofia` - Europe/Sofia
    * `Europe/Stockholm` - Europe/Stockholm
    * `Europe/Tallinn` - Europe/Tallinn
    * `Europe/Tirane` - Europe/Tirane
    * `Europe/Tiraspol` - Europe/Tiraspol
    * `Europe/Ulyanovsk` - Europe/Ulyanovsk
    * `Europe/Uzhgorod` - Europe/Uzhgorod
    * `Europe/Vaduz` - Europe/Vaduz
    * `Europe/Vatican` - Europe/Vatican
    * `Europe/Vienna` - Europe/Vienna
    * `Europe/Vilnius` - Europe/Vilnius
    * `Europe/Volgograd` - Europe/Volgograd
    * `Europe/Warsaw` - Europe/Warsaw
    * `Europe/Zagreb` - Europe/Zagreb
    * `Europe/Zaporozhye` - Europe/Zaporozhye
    * `Europe/Zurich` - Europe/Zurich
    * `Factory` - Factory
    * `GB` - GB
    * `GB-Eire` - GB-Eire
    * `GMT` - GMT
    * `GMT+0` - GMT+0
    * `GMT-0` - GMT-0
    * `GMT0` - GMT0
    * `Greenwich` - Greenwich
    * `HST` - HST
    * `Hongkong` - Hongkong
    * `Iceland` - Iceland
    * `Indian/Antananarivo` - Indian/Antananarivo
    * `Indian/Chagos` - Indian/Chagos
    * `Indian/Christmas` - Indian/Christmas
    * `Indian/Cocos` - Indian/Cocos
    * `Indian/Comoro` - Indian/Comoro
    * `Indian/Kerguelen` - Indian/Kerguelen
    * `Indian/Mahe` - Indian/Mahe
    * `Indian/Maldives` - Indian/Maldives
    * `Indian/Mauritius` - Indian/Mauritius
    * `Indian/Mayotte` - Indian/Mayotte
    * `Indian/Reunion` - Indian/Reunion
    * `Iran` - Iran
    * `Israel` - Israel
    * `Jamaica` - Jamaica
    * `Japan` - Japan
    * `Kwajalein` - Kwajalein
    * `Libya` - Libya
    * `MET` - MET
    * `MST` - MST
    * `MST7MDT` - MST7MDT
    * `Mexico/BajaNorte` - Mexico/BajaNorte
    * `Mexico/BajaSur` - Mexico/BajaSur
    * `Mexico/General` - Mexico/General
    * `NZ` - NZ
    * `NZ-CHAT` - NZ-CHAT
    * `Navajo` - Navajo
    * `PRC` - PRC
    * `PST8PDT` - PST8PDT
    * `Pacific/Apia` - Pacific/Apia
    * `Pacific/Auckland` - Pacific/Auckland
    * `Pacific/Bougainville` - Pacific/Bougainville
    * `Pacific/Chatham` - Pacific/Chatham
    * `Pacific/Chuuk` - Pacific/Chuuk
    * `Pacific/Easter` - Pacific/Easter
    * `Pacific/Efate` - Pacific/Efate
    * `Pacific/Enderbury` - Pacific/Enderbury
    * `Pacific/Fakaofo` - Pacific/Fakaofo
    * `Pacific/Fiji` - Pacific/Fiji
    * `Pacific/Funafuti` - Pacific/Funafuti
    * `Pacific/Galapagos` - Pacific/Galapagos
    * `Pacific/Gambier` - Pacific/Gambier
    * `Pacific/Guadalcanal` - Pacific/Guadalcanal
    * `Pacific/Guam` - Pacific/Guam
    * `Pacific/Honolulu` - Pacific/Honolulu
    * `Pacific/Johnston` - Pacific/Johnston
    * `Pacific/Kanton` - Pacific/Kanton
    * `Pacific/Kiritimati` - Pacific/Kiritimati
    * `Pacific/Kosrae` - Pacific/Kosrae
    * `Pacific/Kwajalein` - Pacific/Kwajalein
    * `Pacific/Majuro` - Pacific/Majuro
    * `Pacific/Marquesas` - Pacific/Marquesas
    * `Pacific/Midway` - Pacific/Midway
    * `Pacific/Nauru` - Pacific/Nauru
    * `Pacific/Niue` - Pacific/Niue
    * `Pacific/Norfolk` - Pacific/Norfolk
    * `Pacific/Noumea` - Pacific/Noumea
    * `Pacific/Pago_Pago` - Pacific/Pago_Pago
    * `Pacific/Palau` - Pacific/Palau
    * `Pacific/Pitcairn` - Pacific/Pitcairn
    * `Pacific/Pohnpei` - Pacific/Pohnpei
    * `Pacific/Ponape` - Pacific/Ponape
    * `Pacific/Port_Moresby` - Pacific/Port_Moresby
    * `Pacific/Rarotonga` - Pacific/Rarotonga
    * `Pacific/Saipan` - Pacific/Saipan
    * `Pacific/Samoa` - Pacific/Samoa
    * `Pacific/Tahiti` - Pacific/Tahiti
    * `Pacific/Tarawa` - Pacific/Tarawa
    * `Pacific/Tongatapu` - Pacific/Tongatapu
    * `Pacific/Truk` - Pacific/Truk
    * `Pacific/Wake` - Pacific/Wake
    * `Pacific/Wallis` - Pacific/Wallis
    * `Pacific/Yap` - Pacific/Yap
    * `Poland` - Poland
    * `Portugal` - Portugal
    * `ROC` - ROC
    * `ROK` - ROK
    * `Singapore` - Singapore
    * `Turkey` - Turkey
    * `UCT` - UCT
    * `US/Alaska` - US/Alaska
    * `US/Aleutian` - US/Aleutian
    * `US/Arizona` - US/Arizona
    * `US/Central` - US/Central
    * `US/East-Indiana` - US/East-Indiana
    * `US/Eastern` - US/Eastern
    * `US/Hawaii` - US/Hawaii
    * `US/Indiana-Starke` - US/Indiana-Starke
    * `US/Michigan` - US/Michigan
    * `US/Mountain` - US/Mountain
    * `US/Pacific` - US/Pacific
    * `US/Samoa` - US/Samoa
    * `UTC` - UTC
    * `Universal` - Universal
    * `W-SU` - W-SU
    * `WET` - WET
    * `Zulu` - Zulu
    * `localtime` - localtime
    """
    auth_tachograph_card: Annotated[
        AnyUrl | None, Field(title="Tachograph card for authorization")
    ] = None
    password_authentication_enabled: bool | None = None
    active_in_countries: list[AnyUrl] | None = None
