"""Auto-generated Pydantic models for Navirec API.

DO NOT EDIT THIS FILE MANUALLY.
Generated from docs/openapi-navirec-1.45.0.json using:
    uv run python scripts/generate_models.py

To regenerate after API spec updates:
    1. Download new OpenAPI spec to docs/
    2. Update OPENAPI_SPEC path in scripts/generate_models.py
    3. Run: uv run python scripts/generate_models.py
"""

# generated by datamodel-codegen:
#   filename:  tmp44nb2t7r.json
#   timestamp: 2026-01-01T13:22:34+00:00

from __future__ import annotations

from datetime import date, time
from decimal import Decimal
from typing import Any
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, conint, constr


class Sensor(BaseModel):
    id: UUID | None = None
    url: AnyUrl | None = None
    vehicle: AnyUrl | None = None
    interpretation: str | None = None
    name: constr(max_length=128) | None = None
    name_display: str | None = None
    slug: constr(pattern=r"^[-a-zA-Z0-9_]+$") | None = None
    icon: AnyUrl | None = None
    icon_template_vars: Any | None = None
    color: str | None = None
    min_value: int | None = Field(None, title="Minimum value")
    max_value: int | None = Field(None, title="Maximum value")
    show_in_map: bool
    show_in_list: bool
    show_in_icon: bool
    show_in_chart: bool
    show_in_report: bool
    sort_order: int | None = None
    chart_axis_id: str | None = Field(None, title="Chart exit ID")


class Vehicle(BaseModel):
    id: UUID | None = None
    url: AnyUrl | None = None
    account: AnyUrl | None = None
    secondary_accounts: list[AnyUrl] | None = None
    country: str | None = None
    registration: str | None = None
    name: constr(max_length=64) | None = ""
    name_display: str | None = None
    active: bool | None = None
    accountable_user: AnyUrl | None = None
    driver: AnyUrl | None = None
    vehicle_groups: list[AnyUrl] | None = None
    workhours: list[list[time]] | None = Field(
        None, max_length=7, title="Work hours per day"
    )
    error_state_threshold: str | None = None
    fuel_events_enabled: bool | None = None
    fuel_used_source: str | None = None
    """
    Which data source should be used in the main fuel used field.
    """
    total_distance_enabled: bool | None = None
    total_engine_time_enabled: bool | None = None
    eco_score_enabled: bool | None = None
    last_activity_enabled: bool | None = None
    """
    Should the last activity info be used in the web/mobile apps to display vehicle state
    """
    country_split_enabled: bool | None = None
    daily_split_times_enabled: bool | None = None
    hide_private_trips: bool | None = None
    history_optimization_enabled: bool | None = None
    """
    Should the vehicle history data be optimized in the API for playback and integrations?
    """
    switched_by_ignition: bool | None = None
    average_fuel_consumption: Decimal | None = None
    """
    L/100km
    """
    hourly_fuel_consumption: Decimal | None = None
    """
    L/h
    """
    average_co2_emission: conint(ge=-2147483648, le=2147483647) | None = None
    """
    g/km
    """
    hourly_co2_emission: conint(ge=-2147483648, le=2147483647) | None = None
    """
    g/h
    """
    trip_tariff: Decimal | None = None
    """
    cost/km
    """
    fuel_tank_capacities: list[int] | None = None
    fuel_tanked_thresholds: list[int] | None = None
    fuel_removed_thresholds: list[int] | None = None
    tachograph_enabled: bool | None = None
    auth_tachograph_card: AnyUrl | None = Field(
        None, title="Tachograph card for authorization"
    )
    tachograph_lock_card: AnyUrl | None = Field(
        None, title="Company card used to lock the tachograph"
    )
    tachograph_locked_at: AwareDatetime | None = None
    """
    Datetime when the tachograph was locked with the current locking card.
    """
    make: constr(max_length=100) | None = None
    model: constr(max_length=100) | None = None
    type: constr(max_length=100) | None = None
    vin: constr(max_length=40) | None = None
    color: constr(max_length=20) | None = None
    fuel_type: str | Any | None = None
    engine_displacement: conint(ge=-2147483648, le=2147483647) | None = None
    manufacturing_year: int | None = None
    first_registration_date: date | None = None
    leasing_start: date | None = None
    leasing_end: date | None = None
    leasing_period_mileage: conint(ge=0, le=2147483647) | None = None
    leasing_period_fee: Decimal | None = None
    additional_fields: Any | None = None


class Location(BaseModel):
    type: str | None = None
    coordinates: list[float] | None = Field(None, max_length=2, min_length=2)


class Trail(BaseModel):
    type: str | None = None
    coordinates: list[list[float]] | None = Field(
        None, examples=[[[0, 0], [1, 0], [1, 1]]], min_length=2
    )


class VehicleState(BaseModel):
    id: UUID | None = None
    vehicle: AnyUrl | None = None
    time: AwareDatetime | None = None
    location: Location | None = Field(
        None, examples=[{"type": "Point", "coordinates": [24.76271, 59.416163]}]
    )
    """
    Geojson geometry object format
    """
    trail: Trail | None = Field(
        None, examples=[{"type": "LineString", "coordinates": [[0, 0], [1, 0], [1, 1]]}]
    )
    """
    Geojson geometry object format
    """
    eco_score: float | None = None
    activity: str | None = None
    activity_started_at: AwareDatetime | None = None
    activity_distance: float | None = None
    activity_engine_time: float | None = None
    received_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None
    interpolated_at: AwareDatetime | None = None
    streamed_at: AwareDatetime | None = None
    accelerator: float | None = None
    accumulated_distance: int | None = None
    accumulated_engine_time: float | None = None
    adblue_level_litres: float | None = None
    adblue_level_percent: float | None = None
    alarm: bool | None = None
    altitude: int | None = None
    ambient_air_temperature: float | None = None
    analog_input_1: int | None = None
    analog_input_2: int | None = None
    analog_input_3: int | None = None
    analog_input_4: int | None = None
    auxiliary_heater: bool | None = None
    axle_weight_1: int | None = None
    axle_weight_10: int | None = None
    axle_weight_11: int | None = None
    axle_weight_12: int | None = None
    axle_weight_13: int | None = None
    axle_weight_14: int | None = None
    axle_weight_15: int | None = None
    axle_weight_2: int | None = None
    axle_weight_3: int | None = None
    axle_weight_4: int | None = None
    axle_weight_5: int | None = None
    axle_weight_6: int | None = None
    axle_weight_7: int | None = None
    axle_weight_8: int | None = None
    axle_weight_9: int | None = None
    battery_level: int | None = None
    battery_voltage: float | None = None
    break_time: float | None = None
    can_fuel_level_percent: float | None = None
    can_state_1: int | None = None
    can_state_2: int | None = None
    can_state_3: int | None = None
    can_state_4: int | None = None
    charging_cable_connected: bool | None = None
    cruise_control: bool | None = None
    daily_driving_time: float | None = None
    daily_work_time: float | None = None
    digital_input_1: bool | None = None
    digital_input_2: bool | None = None
    digital_input_3: bool | None = None
    digital_input_4: bool | None = None
    digital_input_5: bool | None = None
    digital_input_6: bool | None = None
    digital_input_7: bool | None = None
    digital_input_8: bool | None = None
    digital_output_1: bool | None = None
    digital_output_2: bool | None = None
    digital_output_3: bool | None = None
    digital_output_4: bool | None = None
    door_states: str | None = None
    driver_1_card_id: str | None = None
    driver_1_card_present: bool | None = None
    driver_1_ibutton_id: str | None = None
    driver_1_rfid_id: str | None = None
    driver_1_time_state: int | None = None
    driver_1_working_state: int | None = None
    driver_2_card_id: str | None = None
    driver_2_card_present: bool | None = None
    driver_2_ibutton_id: str | None = None
    driver_2_rfid_id: str | None = None
    driver_2_time_state: int | None = None
    driver_2_working_state: int | None = None
    driver_additional_information: str | None = None
    driver_card_issuing_member_state: int | None = None
    driver_cumulative_break_time: float | None = None
    driver_cumulative_driving_time: float | None = None
    driver_daily_driving_time_exceeds_count: int | None = None
    driver_end_last_daily_rest: str | None = None
    driver_end_last_weekly_rest: str | None = None
    driver_end_second_last_weekly_rest: str | None = None
    driver_load_unload_time: float | None = None
    driver_min_daily_rest: float | None = None
    driver_min_weekly_rest: float | None = None
    driver_name: str | None = None
    driver_next_driving_duration: float | None = None
    driver_next_rest_duration: float | None = None
    driver_open_compensation_2nd_week_before_last: float | None = None
    driver_open_compensation_last_week: float | None = None
    driver_open_compensation_week_before_last: float | None = None
    driver_remaining_current_driving_time: float | None = None
    driver_remaining_current_rest_time: float | None = None
    driver_remaining_shift_driving_time: float | None = None
    driver_remaining_weekly_driving_time: float | None = None
    driver_selected_activity_duration: float | None = None
    driver_surname: str | None = None
    driver_time_until_next_break: float | None = None
    driver_time_until_next_daily_rest: float | None = None
    driver_time_until_next_weekly_rest: float | None = None
    driving_time: float | None = None
    dtc_count: int | None = None
    eco_extreme_braking_events: int | None = None
    eco_harsh_acceleration_events: int | None = None
    eco_harsh_braking_events: int | None = None
    eco_harsh_cornering_events: int | None = None
    elect_battery_temperature: float | None = None
    elect_energy: int | None = None
    elect_recharge_distance: int | None = None
    elect_soc: int | None = None
    engine_absolute_load: float | None = None
    engine_coolant_temperature: float | None = None
    engine_oil_temperature: float | None = None
    engine_power: float | None = None
    engine_speed: float | None = None
    fuel_level: float | None = None
    fuel_level_1: float | None = None
    fuel_level_2: float | None = None
    fuel_level_3: float | None = None
    fuel_level_4: float | None = None
    fuel_level_5: float | None = None
    fuel_level_6: float | None = None
    fuel_level_ewma: float | None = None
    fuel_rate: float | None = None
    fuel_temperature: float | None = None
    fuel_temperature_1: float | None = None
    fuel_temperature_5: float | None = None
    fuel_temperature_6: float | None = None
    heading: int | None = None
    humidity_1: float | None = None
    humidity_2: float | None = None
    hv_battery_charging: bool | None = None
    ignition: bool | None = None
    intake_maf: float | None = None
    keypad_code: str | None = None
    notification: bool | None = None
    panic: bool | None = None
    satellites: int | None = None
    scooter_alarm: int | None = None
    scooter_buzzer: bool | None = None
    scooter_charging: bool | None = None
    scooter_error: int | None = None
    speed: int | None = None
    starter_blocked: bool | None = None
    supply_voltage: float | None = None
    tacho_current_time: str | None = None
    tacho_drivers_hours_rules_pre_warning_time_delay: float | None = None
    tacho_next_calibration_date: str | None = None
    tacho_out_of_scope_condition: int | None = None
    teltonika_external_digital_sensor_1: bool | None = None
    teltonika_temperature_probe_5: float | None = None
    teltonika_temperature_probe_6: float | None = None
    temperature_1: float | None = None
    temperature_2: float | None = None
    temperature_3: float | None = None
    temperature_4: float | None = None
    temperature_5: float | None = None
    temperature_6: float | None = None
    temperature_7: float | None = None
    temperature_8: float | None = None
    timezone_offset: float | None = None
    total_distance: int | None = None
    total_engine_time: float | None = None
    total_fuel_used: float | None = None
    two_weekly_driving_time: float | None = None
    two_weekly_work_time: float | None = None
    vehicle_locked: bool | None = None
    vehicle_weight: int | None = None
    weekly_driving_time: float | None = None
    weekly_work_time: float | None = None
    working_state: int | None = None
    work_time: float | None = None


class Account(BaseModel):
    id: UUID | None = None
    url: AnyUrl | None = None
    name: constr(max_length=100)
    reference: conint(ge=-9223372036854775808, le=9223372036854775807) | None = Field(
        None, title="Reference number"
    )
    registry_code: constr(max_length=20) | None = None
    vat_number: constr(max_length=20) | None = Field(
        None, title="VAT identification number"
    )
    default_language: str | Any | None = None
    """
    If blank Partner's default language will be chosen
    """
    timezone: str | Any | None = None
    """
    If blank Partner's timezone will be chosen
    """
    auth_tachograph_card: AnyUrl | None = Field(
        None, title="Tachograph card for authorization"
    )
    password_authentication_enabled: bool | None = None
    active_in_countries: list[AnyUrl] | None = None


class Interpretation(BaseModel):
    id: int | None = None
    url: AnyUrl | None = None
    key: constr(max_length=50) | None = None
    name: constr(max_length=50) | None = None
    name_display: str | None = None
    unit: str | Any | None = None
    unit_conversion: str | Any | None = None
    unit_display: str | None = None
    data_type: str | Any | None = None
    multiple_value: bool | None = None
    decimal_places: conint(ge=0, le=32767) | None = None
    icon: AnyUrl | None = None
    icon_template_vars: dict[str, Any] | None = Field(
        None, examples=[{"field_name": "field_value"}]
    )
    """
    JSON object
    """
    color: (
        constr(pattern=r"^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$", max_length=25) | None
    ) = None
    api_field: constr(max_length=50) | None = None
    choices: Any | None = None
